"""The population, written down and hashed.

A manifest is the inputs of a sweep and nothing else: which seed, how many
patterns, and the exact bytes, options and offsets of every case. It carries no
answers, so the same file can be handed to pcre2, to the Python interpreter, to
the generated Go and to the generated JavaScript and mean the same thing to all
four. Its hash is what a result set names, which is how a count of checks and a
set of cases stay attached to each other.

The envelope is the conformance corpora's — the same schema number, the same
"a section is a list with something in it" rule, the same committed spelling —
because a runner should not have to be told which kind of document it was given.
The options are the numbers the engine takes rather than their names, for the
same reason: only Python has the tables.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..engine import spec
from ..oracle import conformance
from . import population as population_module
from .population import Case, Trial, population

NOTE = (
    "The inputs of one differential sweep, generated by pcrevera.sweep. Every "
    "case is a function of three numbers in this header — the seed, the "
    "subject count, and where the structured population ends — and of its own "
    "index, so this file can be rebuilt rather than kept, and a failure can "
    "name this file's hash and an index instead of a pattern. Nothing here is "
    "an answer: the same manifest is replayed through "
    "pcre2, the Python interpreter, the generated Go and the generated "
    "JavaScript, and what they say about it lives in the result document that "
    "names this file's hash."
)

DEFAULT_SEED = 20260803

DEFAULT_BUDGET = {"cost": 200_000, "stack": 1 << 16, "memory": 1 << 22}
"""What a run is allowed when the certificate cannot say.

A pattern with no finite bound has no sufficient limit to be run at, and a
pattern whose bound is astronomically large has one no sweep could wait for. In
both cases the run gets this instead, and the case is counted as capped rather
than as certified: a ResourceExceeded under a capped budget is a decline of the
oracle policy of DESIGN.md section 1, never a disagreement.
"""


@dataclass(frozen=True)
class Manifest:
    """A manifest as it was read back: the cases, the budget, and the hash."""

    seed: int
    cases: tuple[Case, ...]
    budget: dict[str, int]
    digest: str
    shape: dict[str, int]
    document: dict[str, Any]
    """The document these came out of. Kept rather than rebuilt, so the hash
    above is the hash of the bytes a run writes down and not of a second
    encoding that has to be shown to be the same one."""


def encode_trial(trial: Trial) -> dict[str, Any]:
    """One trial as the manifest spells it: what to ask, and nothing else.

    Every trial record of a result document opens with exactly this, so a
    field added to a trial arrives in both files rather than in the inputs
    alone — the runners read their trials out of the record, never out of the
    manifest.
    """
    return {
        "subject": trial.subject.hex(),
        "matchFlags": conformance.flags(trial.match_options, spec.MATCH_OPTIONS),
        "start": trial.start,
    }


def encode(case: Case) -> dict[str, Any]:
    """One case as the manifest spells it."""
    return {
        "seed": case.seed,
        "index": case.index,
        "family": case.family,
        "pattern": case.pattern.hex(),
        "flags": conformance.flags(case.options, spec.COMPILE_OPTIONS),
        "newline": spec.NEWLINE_CONVENTIONS[case.newline],
        "bsr": spec.BSR_CONVENTIONS[case.bsr],
        "maxlen": case.maxlen,
        "trials": [encode_trial(trial) for trial in case.trials],
    }


def decode(entry: dict[str, Any]) -> Case:
    """The same case, read back out of one."""
    return Case(
        seed=entry["seed"],
        index=entry["index"],
        family=entry["family"],
        pattern=bytes.fromhex(entry["pattern"]),
        options=conformance.names(entry["flags"], spec.COMPILE_OPTIONS),
        newline=conformance.convention(entry["newline"], spec.NEWLINE_CONVENTIONS),
        bsr=conformance.convention(entry["bsr"], spec.BSR_CONVENTIONS),
        trials=tuple(
            Trial(
                subject=bytes.fromhex(trial["subject"]),
                match_options=conformance.names(trial["matchFlags"], spec.MATCH_OPTIONS),
                start=trial["start"],
            )
            for trial in entry["trials"]
        ),
        maxlen=entry["maxlen"],
    )


def document(
    seed: int,
    cases: tuple[Case, ...],
    *,
    structured: int,
    hostile: int,
    subjects: int,
    stride: int = 1,
    budget: dict[str, int] | None = None,
) -> dict[str, Any]:
    """A whole manifest as plain JSON data.

    The header carries the numbers the case list was generated from, so a
    reader who has only this file can rebuild it and get the same hash.
    """
    return conformance.document(
        NOTE,
        [encode(one) for one in cases],
        seed=seed,
        structured=structured,
        hostile=hostile,
        subjects=subjects,
        stride=stride,
        budget=dict(budget or DEFAULT_BUDGET),
    )


def build(
    seed: int = DEFAULT_SEED,
    *,
    structured: int = population_module.STRUCTURED,
    hostile: int = population_module.HOSTILE,
    subjects: int = population_module.SUBJECTS,
    stride: int = 1,
    budget: dict[str, int] | None = None,
) -> dict[str, Any]:
    """Generate a population and write it down in one step."""
    cases = population(
        seed, structured=structured, hostile=hostile, subjects=subjects, stride=stride
    )
    return document(
        seed,
        cases,
        structured=structured,
        hostile=hostile,
        subjects=subjects,
        stride=stride,
        budget=budget,
    )


def text(built: dict[str, Any]) -> str:
    return conformance.text(built)


def digest(built: dict[str, Any]) -> str:
    """The hash a result document names, taken over the committed spelling.

    The text rather than the object, so that the number a run reports is the
    one anybody can recompute from the file with sha256sum.
    """
    return hashlib.sha256(text(built).encode()).hexdigest()


def read(built: dict[str, Any], path: Path | None = None) -> Manifest:
    """A manifest document, decoded into the cases a runner takes."""
    entries = conformance.section(built, "cases", path or Path("manifest"))
    return Manifest(
        seed=built["seed"],
        cases=tuple(decode(entry) for entry in entries),
        budget=dict(built.get("budget") or DEFAULT_BUDGET),
        digest=digest(built),
        shape={name: built[name] for name in ("structured", "hostile", "subjects", "stride")},
        document=built,
    )


def load(path: Path) -> Manifest:
    return read(conformance.read(path), path)
