"""The M2 golden test: DSL -> JSON -> interpreter, over a checked-in artifact.

`tests/golden/toy.tir.json` is regenerated by `python tests/toy.py`, and a diff
there is meant to be read: it is what a change to the DSL, the serializer, or
the toy program looks like from the outside.
"""

from __future__ import annotations

import hashlib

import pytest
import toy

from pcretruste.tir import Cell, Trap, dumps, loads, run, validate


@pytest.fixture(scope="module")
def built():
    program = toy.build()
    validate(program)
    return program


@pytest.fixture(scope="module")
def decoded():
    """The program as the backends and the Lean decoder will see it: from the file."""
    return loads(toy.GOLDEN.read_text())


def test_the_dsl_still_produces_the_checked_in_artifact(built):
    assert dumps(built) == toy.GOLDEN.read_text()


def test_the_artifact_decodes_to_the_program_it_was_written_from(built, decoded):
    assert decoded == built


def test_the_artifact_is_its_own_canonical_form(decoded):
    assert dumps(decoded) == toy.GOLDEN.read_text()


def test_what_comes_back_off_disk_validates(decoded):
    validate(decoded)


def test_the_digest_is_a_function_of_the_program_alone(built):
    from_memory = hashlib.sha256(dumps(built).encode()).hexdigest()
    from_disk = hashlib.sha256(toy.GOLDEN.read_bytes()).hexdigest()
    assert from_memory == from_disk


@pytest.mark.parametrize("n", list(range(0, 16)))
def test_fibonacci_through_the_decoded_artifact(decoded, n):
    out = Cell(0)
    assert run(decoded, "fib", [n, out]) is True
    assert out.value == toy.fibonacci(n)


def test_the_interpreter_agrees_with_the_program_in_memory(built, decoded):
    for n in (7, 11):
        answers = []
        for program in (built, decoded):
            out = Cell(0)
            run(program, "fib", [n, out])
            answers.append(out.value)
        assert answers[0] == answers[1] == toy.fibonacci(n)


def test_an_exhausted_fuel_budget_shows_up_in_the_answer(decoded):
    """The declared variant bounds the loop, so running out is a result, not a hang."""
    out = Cell(0)
    assert run(decoded, "fib", [30, out], fuel=10_000_000) is False


def test_a_stack_deeper_than_its_declared_maximum_traps(decoded):
    with pytest.raises(Trap) as caught:
        run(decoded, "fib", [70, Cell(0)])
    assert caught.value.code == "T-05"


@pytest.mark.parametrize("i", list(range(0, 260, 17)))
def test_the_frozen_table_lookup(decoded, i):
    assert run(decoded, "masked", [i % 256]) == toy.BITS[i % 256 % 8]
