"""What the certificate checker has to answer, in every language.

`certificate.py` is the checker; this is the corpus it is held to. It sits
beside the checker rather than beside the printers, because its subject is the
engine rather than the lowering — the generator reaches across for it the same
way it reaches for the wave 1 restatement in `oracle/conformance.py`.

It exists because a certificate has no way in through the public API, which is
exactly the gap DESIGN.md section 8 asks these corpora to close: without it the
checker would be the one piece of the engine that both backends carried and
neither ran, on the link the design calls tested rather than proved.

A case names a pattern rather than a bytecode listing, so every runner compiles
it with the engine it has and the checker is handed the program that engine
would really run. Two runners that disagree about the bytecode therefore
disagree here, which is the point.

The region tree is the compiler's — it emits one while it still has the AST
in hand — so a case names a pattern and gets the tree that pattern really
compiles to. The cases about trees that are not trees hand the checker one of
their own instead, since no compiler would emit those and the rules that refuse
them still have to be exercised.

The certificates are built by `price` below, which is BOUNDS.md written a
second time in Python. That is deliberate. Writing out four polynomials per
region by hand would be transcription, and transcription is where a corpus
quietly stops describing anything; computing them from the rules means the
exact-minimum cases really are exact, and the one-unit-lower mutations really
are one unit short. What stays hand-written is the verdict of every case, which
is checked at generation time, so a checker that changed its mind breaks the
build instead of rewriting the file it is supposed to be held to.
"""

from __future__ import annotations

import functools
from dataclasses import dataclass, field, replace

from ..oracle import conformance
from ..paths import CONFORMANCE_DIR
from ..tir.interp import Frozen, Seq, StructValue, Tag
from ..tir.types import CAP, CEILING
from . import spec
from .driver import (
    ZERO,
    Certificate,
    CompiledPattern,
    Engine,
    Poly,
    Price,
    Region,
    coef,
)
from .program import program

PATH = CONFORMANCE_DIR / "certificates.json"

NOTE = (
    "Generated by pcretruste.engine.certificate_corpus. Each case compiles a "
    "pattern, hands the engine's bound-certificate checker one certificate for "
    "the program that came out, and asks for the three bounds it prices at "
    "every subject length below. Every implementation of the engine has to "
    "give exactly these answers: the same verdict, and the same number or the "
    "same refusal. A bound of null is the ExceedsBudget of DESIGN.md section "
    "2.4, which is a refusal rather than a number and never a saturated "
    "counter."
)

LENGTHS = (0, 1, 2, 10, 53, 65535, CAP)
"""Subject lengths every case is evaluated at.

Small ones because that is where a bound is a usable number, 53 because it is
where a doubling term runs out of counter, and the cap because a bound has to
refuse rather than wrap at the far end of the range.
"""

KINDS = (("cost", "BkCost"), ("stack", "BkStack"), ("mem", "BkMem"))
"""What the file calls each bound, and what the engine calls the same one."""

DEGREES = spec.DEGREES

SEQUENCE = ("RkRoot", "RkGroup", "RkBranch")
"""The kinds whose code is read straight through, one instruction at a time."""

SIMPLE_OPS = frozenset(
    {
        "OpChar",
        "OpCharCI",
        "OpClass",
        "OpAny",
        "OpAnyNoNL",
        "OpBsr",
        "OpCirc",
        "OpCircM",
        "OpDoll",
        "OpDollE",
        "OpDollM",
        "OpSod",
        "OpEod",
        "OpEodn",
        "OpWordB",
        "OpNotWordB",
    }
)


# --- the arithmetic of BOUNDS.md section 2 ---


def _norm(base: int, coefs) -> Poly:
    """The canonical form, and the saturation point the checker refuses at.

    Python counts as high as it likes and a counter does not, so a bound this
    arithmetic could write down and the engine could not hold is refused here
    rather than later: `price` promises a certificate the checker accepts, and
    the checker answers `CrOverflow` for exactly this.
    """
    if base > CAP or any(one > CAP for one in coefs):
        raise ValueError("a bound past what a counter holds")
    trimmed = tuple(coefs)
    while trimmed and trimmed[-1] == 0:
        trimmed = trimmed[:-1]
    return ZERO if not trimmed else Poly(trimmed, base)


def padd(a: Poly, b: Poly) -> Poly:
    return _norm(max(a.base, b.base), [coef(a, d) + coef(b, d) for d in DEGREES])


def pmul(a: Poly, b: Poly) -> Poly:
    out = [0] * len(DEGREES)
    for left in DEGREES:
        for right in DEGREES:
            product = coef(a, left) * coef(b, right)
            if product == 0:
                continue
            if left + right > spec.MAX_DEGREE:
                raise ValueError("a product past the top power the struct holds")
            out[left + right] += product
    return _norm(a.base * b.base, out)


def flat(p: Poly) -> int | None:
    """The one number this bound is, or None if it is not one number."""
    if p.base != 1 or any(coef(p, d) for d in DEGREES[1:]):
        return None
    return coef(p, 0)


def const(value: int) -> Poly:
    return _norm(1, [value])


STEP = Poly((0, 1))
"""n + 1."""


# --- pricing a region tree, which is BOUNDS.md sections 3 and 4 ---


@dataclass
class Acc:
    work: Poly = ZERO
    stack: Poly = ZERO
    trail: Poly = ZERO
    flow: Poly = ZERO


@dataclass(frozen=True)
class Program:
    """The facts the checker is given, read back out of a compiled pattern."""

    code: tuple[tuple[str, int, int], ...]
    reps: tuple[dict, ...]
    regions: tuple[Region, ...]
    ncap: int
    nregs: int


def read(built: CompiledPattern) -> Program:
    re = built.re
    return Program(
        code=tuple(
            (_variant_of(one, "op"), one.fields["arg"], one.fields["alt"])
            for one in _items(re.fields["code"])
        ),
        reps=tuple(
            {
                key: value.variant if isinstance(value, Tag) else value
                for key, value in one.fields.items()
            }
            for one in _items(re.fields["reps"])
        ),
        regions=tuple(
            Region(
                kind=_variant_of(one, "kind"),
                parent=one.fields["parent"],
                lo=one.fields["lo"],
                hi=one.fields["hi"],
            )
            for one in _items(re.fields["regions"])
        ),
        ncap=re.fields["ncap"],
        nregs=re.fields["nregs"],
    )


def _items(value) -> list[StructValue]:
    assert isinstance(value, Frozen)
    inner = value.inner
    assert isinstance(inner, Seq)
    return [one for one in inner.items if isinstance(one, StructValue)]


def _variant_of(one: StructValue, name: str) -> str:
    tag = one.fields[name]
    assert isinstance(tag, Tag)
    return tag.variant


def _span(prog: Program, priced, kids: list[int], lo: int, hi: int, acc: Acc) -> None:
    """Read a stretch of bytecode, charging every instruction to the flow."""
    tree = prog.regions
    pc = lo
    while pc < hi:
        if kids and tree[kids[0]].lo == pc:
            at = kids.pop(0)
            kid = priced[at]
            if tree[at].hi <= pc or tree[at].hi > hi:
                raise ValueError(f"region {at} is not a child of this span")
            acc.work = padd(acc.work, pmul(acc.flow, kid.work))
            acc.stack = padd(acc.stack, pmul(acc.flow, kid.stack))
            acc.trail = padd(acc.trail, pmul(acc.flow, kid.trail))
            acc.flow = pmul(acc.flow, kid.flow)
            pc = tree[at].hi
            continue
        op = prog.code[pc][0]
        if op in SIMPLE_OPS:
            acc.work = padd(acc.work, acc.flow)
        elif op == "OpSave":
            acc.work = padd(acc.work, acc.flow)
            acc.trail = padd(acc.trail, acc.flow)
        elif op == "OpAccept":
            acc.work = padd(acc.work, acc.flow)
            acc.flow = ZERO
        else:
            raise ValueError(f"{op} at {pc} belongs to a region, not to a span")
        pc += 1


def _alt(priced, kids: list[int]) -> Acc:
    """Every branch is tried, and every one but the last leaves by a jump."""
    acc = Acc()
    for index, child in enumerate(kids):
        kid = priced[child]
        acc.work = padd(acc.work, kid.work)
        acc.stack = padd(acc.stack, kid.stack)
        acc.trail = padd(acc.trail, kid.trail)
        acc.flow = padd(acc.flow, kid.flow)
        if index < len(kids) - 1:
            acc.work = padd(acc.work, padd(const(1), kid.flow))
            acc.stack = padd(acc.stack, const(1))
    return acc


def _repeat(prog: Program, priced, kids: list[int], at: int) -> Acc:
    here = prog.regions[at]
    lo, hi = here.lo, here.hi
    head = prog.code[lo]
    acc = Acc(ZERO, ZERO, ZERO, const(1))
    if head[0] == "OpSplit":
        _span(prog, priced, kids, lo + 1, hi, acc)
        acc.work = padd(acc.work, const(1))
        acc.stack = padd(acc.stack, const(1))
        acc.flow = padd(acc.flow, const(1))
        return acc

    rep = prog.reps[head[1]]
    _span(prog, priced, kids, lo + 3, hi - 1, acc)
    ways = flat(acc.flow)
    if ways is None:
        raise ValueError("a repeat body whose ambiguity grows with the subject")
    bounded = rep["hi"] != spec.NONE
    ceiling = max(rep["lo"], rep["hi"]) if bounded else rep["lo"]
    # One more than the iteration count, because what is counted is passes
    # through the head, and the pass that finds the count spent is a pass.
    rounds = const(ceiling + 1) if bounded else Poly((rep["lo"] + 1, 1))
    if ways > 1:
        exponent = ceiling + 1 if bounded else rep["lo"] + 2
        raised = ways**exponent
        if raised > CAP:
            raise ValueError("a pass count past what a counter holds")
        rounds = const(raised) if bounded else Poly((raised,), ways)

    body, per = acc, const(ways)
    return Acc(
        work=padd(const(1), pmul(rounds, padd(padd(const(2), body.work), per))),
        stack=pmul(rounds, padd(const(1), body.stack)),
        trail=padd(const(1), pmul(rounds, padd(padd(const(1), per), body.trail))),
        flow=pmul(rounds, padd(const(1), per)),
    )


def price(prog: Program) -> Certificate:
    """The smallest certificate the checker accepts for this program.

    Bottom up, because a region is priced from what its children cost, which is
    the same induction the checker walks and the same one Layer A will. This is
    what the analyzer will do; here it builds the corpus, so that an
    exact-minimum case really is exact and a mutation of one really is a unit
    short.
    """
    tree = prog.regions
    kids: dict[int, list[int]] = {at: [] for at in range(len(tree))}
    for at, region in enumerate(tree):
        if at:
            kids[region.parent].append(at)
    priced: dict[int, Acc] = {}
    for at in reversed(range(len(tree))):
        region = tree[at]
        mine = list(kids[at])
        if region.kind in SEQUENCE:
            acc = Acc(ZERO, ZERO, ZERO, const(1))
            _span(prog, priced, mine, region.lo, region.hi, acc)
        elif region.kind == "RkAlt":
            acc = _alt(priced, mine)
            mine = []
        elif region.kind == "RkRepeat":
            acc = _repeat(prog, priced, mine, at)
        else:
            raise ValueError(f"no composition rule for {region.kind}")
        if mine:
            raise ValueError(f"region {at} left children unpriced")
        priced[at] = acc

    root = priced[0]
    novec = (prog.ncap + 1) * 2
    setup = (prog.nregs + novec) * spec.REG_SIZE
    deliver = novec * spec.REG_SIZE
    reset = prog.nregs * spec.REG_SIZE
    scratch = ZERO
    for quantity, esize in (("stack", spec.BT_SIZE), ("trail", spec.UNDO_SIZE)):
        held = getattr(root, quantity)
        capacity = (
            ZERO
            if held == ZERO
            else padd(const(spec.GROW_MIN), pmul(held, const(spec.GROW_FACTOR)))
        )
        scratch = padd(scratch, pmul(capacity, const(esize)))
    return Certificate(
        prices=tuple(
            Price(work=one.work, outs=one.flow, stack=one.stack, trail=one.trail)
            for one in (priced[at] for at in range(len(tree)))
        ),
        # The 3 and the 2 are the two bounds BOUNDS.md section 5 derives from
        # the growth schedule rather than numbers the matcher holds: the
        # buffers a doubling run allocates come to twice its final reservation
        # and the ones it copies out of to one more, and holding both at once
        # is what makes the memory peak twice the reservation.
        cost=padd(
            const(setup + deliver),
            padd(
                pmul(
                    padd(
                        const(reset),
                        padd(root.work, pmul(root.trail, const(spec.REG_SIZE))),
                    ),
                    STEP,
                ),
                pmul(scratch, const(3)),
            ),
        ),
        stack=root.stack,
        mem=padd(const(setup), pmul(scratch, const(2))),
    )


# --- the cases ---


@dataclass(frozen=True)
class Case:
    """One certificate, the program it prices, and the verdict it has to draw."""

    name: str
    note: str
    check: str
    pattern: bytes
    cert: Certificate
    config: str = "CfgBacktrack"
    regions: tuple[Region, ...] | None = None
    """A region table to put in place of the one the compiler emitted.

    Every rule that holds the tree to the bytecode needs a tree that does not,
    and since the compiler is what emits trees now, the only way to write one
    down is to hand it to the checker where the compiler's would have been.
    """
    bounds: tuple[dict, ...] = field(default=(), compare=False)
    """What the file records this certificate evaluating to.

    Out of the comparison, so that the round-trip check is about the case and
    not about numbers the case never claimed.
    """

    def subject(self) -> CompiledPattern:
        """The compiled pattern the checker is handed, doctored tree and all."""
        built = compiled(self.pattern)
        return built if self.regions is None else built.with_regions(self.regions)


ENGINE = Engine()


@functools.lru_cache(maxsize=None)
def compiled(pattern: bytes) -> CompiledPattern:
    """A compiled pattern, remembered.

    Compiling goes through the reference interpreter, which is slow enough that
    the corpus and its tests compiling `abc` two dozen times each is worth
    avoiding. A compiled pattern is immutable, so one serves every caller.
    """
    built = ENGINE.compile_pattern(pattern)
    if not isinstance(built, CompiledPattern):
        raise AssertionError(f"{pattern!r} does not compile: {built}")
    return built


def region(kind: str, parent: int, lo: int, hi: int) -> Region:
    return Region(kind=kind, parent=parent, lo=lo, hi=hi)


def root(hi: int) -> Region:
    return region("RkRoot", spec.NONE, 0, hi)


def minimal(pattern: bytes) -> Certificate:
    """The exact-minimum certificate for a pattern's own region tree."""
    return price(read(compiled(pattern)))


def unpriced(count: int) -> Certificate:
    """A certificate that claims nothing, for the cases about the tree itself."""
    return Certificate(prices=(Price(),) * count)


def less(cert: Certificate, *path) -> Certificate:
    """The same certificate with one coefficient a single unit lower.

    The path is either a whole-pattern bound and a power — `("cost", 1)` — or a
    region, one of the four things it is priced for, and a power.
    """
    *where, degree = path
    if len(where) == 1:
        return replace(cert, **{where[0]: _drop(getattr(cert, where[0]), degree)})
    at, quantity = where
    prices = list(cert.prices)
    prices[at] = replace(
        prices[at], **{quantity: _drop(getattr(prices[at], quantity), degree)}
    )
    return replace(cert, prices=tuple(prices))


def _drop(p: Poly, degree: int) -> Poly:
    if coef(p, degree) < 1:
        raise ValueError(f"there is no unit at degree {degree} to take away")
    coefs = [coef(p, d) for d in DEGREES]
    coefs[degree] -= 1
    return _norm(p.base, coefs)


def claiming(cert: Certificate, **over) -> Certificate:
    return replace(cert, **over)


LITERAL = minimal(b"abc")
CAPTURE = minimal(b"(a)")
ALTERNATION = minimal(b"a|b")
OPTIONAL = minimal(b"a?")
LAZY = minimal(b"a??")
STAR = minimal(b"a*")
COUNTED = minimal(b"a{2,5}")
GROUPED = minimal(b"(ab)*c")
LOOPED_ALT = minimal(b"(a|b)*c")
AMBIGUOUS = minimal(b"(?:a|a){0,3}")
EXPONENTIAL = minimal(b"(?:a|a)*")
EMPTY_BRANCH = minimal(b"(a|)")
UNCAPTURED = minimal(b"(?:abc)")

CASES: list[Case] = [
    Case(
        "literal",
        "Three characters and an accept. The whole cost is one visit per "
        "instruction at each of the n + 1 starting positions, plus the register "
        "file and the ovector, sized and zeroed once, cleared again per "
        "attempt, and copied back out when the match is found.",
        "CrOk",
        b"abc",
        LITERAL,
    ),
    Case(
        "capture",
        "The same four instructions, two of them saves. A save records an undo "
        "entry, so this pattern needs a trail where the literal needed none — "
        "which is the whole point of pricing the opcodes rather than counting "
        "them.",
        "CrOk",
        b"(a)",
        CAPTURE,
    ),
    Case(
        "alternation",
        "A split, two branches, and the jump the first one leaves by. The "
        "region is entered once and both branches are tried, so the ambiguity "
        "is two and the accept downstream is charged twice.",
        "CrOk",
        b"a|b",
        ALTERNATION,
    ),
    Case(
        "an-empty-alternation-branch",
        "`(a|)` compiles the second branch to nothing at all, so its region "
        "covers no instruction. That is legal for a branch and for nothing "
        "else: the alternation reads its shape off the branch list, so the "
        "branch has to be there whether or not it holds anything.",
        "CrOk",
        b"(a|)",
        EMPTY_BRANCH,
    ),
    Case(
        "optional",
        "One split whose arms are the body and what follows it.",
        "CrOk",
        b"a?",
        OPTIONAL,
    ),
    Case(
        "lazy-optional",
        "The same shape with the split's arms the other way round, which costs "
        "exactly the same and is why the rule takes either order.",
        "CrOk",
        b"a??",
        LAZY,
    ),
    Case(
        "star",
        "An unbounded repetition. Past the minimum count an iteration that "
        "consumed nothing is the last one, so the head is reached at most "
        "n + 2 times and the cost comes out quadratic once the starting "
        "positions are counted in.",
        "CrOk",
        b"a*",
        STAR,
    ),
    Case(
        "counted",
        "A bounded one, where the declared maximum is what stops it and the "
        "bound has no term in n at all.",
        "CrOk",
        b"a{2,5}",
        COUNTED,
    ),
    Case(
        "grouped-repeat",
        "A capturing group inside a star, followed by a literal. The group is "
        "entered once per iteration and its saves are charged there, so the "
        "trail grows with the loop rather than with the program.",
        "CrOk",
        b"(ab)*c",
        GROUPED,
    ),
    Case(
        "alternation-inside-a-loop",
        "The same shape with two branches in the group, and the bound comes "
        "out exponential. Structurally it is: the loop hands the next iteration "
        "one flow per way the body finished, and nothing in these rules knows "
        "that `a` and `b` cannot both match the same byte. The bound may "
        "overestimate and never underestimate (DESIGN.md section 5), and a "
        "first-byte disjointness rule is what would sharpen this one.",
        "CrOk",
        b"(a|b)*c",
        LOOPED_ALT,
    ),
    Case(
        "ambiguous-body-bounded",
        "A body with two ways to match the same character, repeated at most "
        "three times. Each iteration doubles the ways into the next, so the "
        "flow through the head is a power of two and the bound stays a number.",
        "CrOk",
        b"(?:a|a){0,3}",
        AMBIGUOUS,
    ),
    Case(
        "exponential",
        "The same body with no upper bound, which is where the growing base "
        "comes from: the head is reached n + 2 times, so the flow is a "
        "multiple of 2^n and the bound saturates within a few dozen bytes of "
        "subject. That is the honest answer rather than a number nobody could "
        "budget for.",
        "CrOk",
        b"(?:a|a)*",
        EXPONENTIAL,
    ),
    Case(
        "linear-claim-that-holds",
        "The class claim of DESIGN.md section 6, held to the shape it names: "
        "a literal really does cost at most c * (n + 1).",
        "CrOk",
        b"abc",
        claiming(LITERAL, complexity="CcLinear"),
    ),
    Case(
        "linear-claim-with-a-square",
        "A star does not, and saying so does not make it so.",
        "CrNotLinear",
        b"a*",
        claiming(STAR, complexity="CcLinear"),
    ),
    Case(
        "linear-claim-with-a-growing-base",
        "Nor does an exponential bound, however small its coefficient.",
        "CrNotLinear",
        b"(?:a|a)*",
        claiming(EXPONENTIAL, complexity="CcLinear"),
    ),
    Case(
        "over-claimed-to-every-ceiling",
        "A certificate may be generous, as long as it is generous in every "
        "coefficient at once. These reach exactly the three ceilings at n = 0: "
        "the counter's saturation point for cost, the deepest stack a limit "
        "could name, and the section 3 byte ceiling for memory. What a caller "
        "reads back is what the certificate names, not what the checker "
        "computed.",
        "CrOk",
        b"abc",
        claiming(
            LITERAL,
            cost=Poly((CAP - 12, 12)),
            stack=const(spec.MAX_STACK),
            mem=const(CEILING),
        ),
    ),
    Case(
        "over-claimed-past-every-ceiling",
        "One unit more of each, which no limit could accept, so none of the "
        "three is a number any more. The three ceilings differ, which is the "
        "whole difference between the projections.",
        "CrOk",
        b"abc",
        claiming(
            LITERAL,
            cost=Poly((CAP - 11, 12)),
            stack=const(spec.MAX_STACK + 1),
            mem=const(CEILING + 1),
        ),
    ),
    Case(
        "past-the-memory-ceiling-and-still-a-cost",
        "One IR byte more than the largest reservation there is, claimed as "
        "both. It is refused as memory and is a perfectly ordinary amount of "
        "work, which is the whole reason the three projections carry their own "
        "ceilings rather than sharing the counter's.",
        "CrOk",
        b"abc",
        claiming(LITERAL, cost=Poly((CEILING + 1, 12)), mem=const(CEILING + 1)),
    ),
    # --- the same length, a different program ---
    Case(
        "an-uncaptured-certificate-on-a-capture",
        "Four instructions and the same three regions over the same three "
        "ranges either way, and the only difference is that two of the "
        "instructions are saves. A save records an undo entry, so the "
        "certificate for the group that captures nothing is two entries short "
        "of the one that does. A checker given only a length could not tell "
        "these two programs apart at all.",
        "CrRegionTrail",
        b"(a)",
        UNCAPTURED,
    ),
    Case(
        "straight-line-certificate-on-a-branching-program",
        "Five instructions either way. A split is not an instruction a region "
        "may hold loose: the tree has to say which construct it belongs to, or "
        "nothing prices the choice it makes.",
        "CrOpcode",
        b"a|b",
        unpriced(1),
        regions=(root(5),),
    ),
    Case(
        "branching-certificate-on-a-straight-line-program",
        "And the other way round, where the alternation region is pointed at "
        "code that has no split in it.",
        "CrShape",
        b"abcd",
        unpriced(4),
        regions=(
            root(5),
            region("RkAlt", 0, 0, 4),
            region("RkBranch", 1, 1, 2),
            region("RkBranch", 1, 3, 4),
        ),
    ),
    Case(
        "repeat-certificate-on-the-other-repetition",
        "Two repetitions, and a region covering the first one\'s header and the "
        "second one\'s tail. Nothing has to be recorded to make this refusable: "
        "each of the four opcodes names its own repetition, and the range pins "
        "the head, the body and the exit, so a repeat region cannot be about a "
        "quantifier other than the one it covers.",
        "CrShape",
        b"a*a*",
        unpriced(2),
        regions=(root(11), region("RkRepeat", 0, 0, 10)),
    ),
    # --- the configuration the certificate is for ---
    Case(
        "configuration-mismatch",
        "A certificate for the Pike VM says nothing about the backtracking "
        "one, whatever its numbers are.",
        "CrConfig",
        b"abc",
        claiming(LITERAL, config="CfgPike"),
    ),
    Case(
        "no-rules-for-pike-yet",
        "The Pike VM charges differently enough that borrowing these rules for "
        "it would be a guess. It gets its own, later in M5.",
        "CrNoRules",
        b"abc",
        claiming(LITERAL, config="CfgPike"),
        config="CfgPike",
    ),
    Case(
        "no-rules-for-the-memoized-path",
        "And the memoized path waits for M9, memo table and all.",
        "CrNoRules",
        b"abc",
        claiming(LITERAL, config="CfgMemo"),
        config="CfgMemo",
    ),
    # --- one price per region ---
    Case(
        "fewer-prices-than-regions",
        "A region nobody priced is a region the composition rules would read a "
        "zero out of.",
        "CrPrices",
        b"a*",
        claiming(STAR, prices=STAR.prices[:-1]),
    ),
    Case(
        "more-prices-than-regions",
        "And a price nobody emitted a region for is a claim about nothing.",
        "CrPrices",
        b"a*",
        claiming(STAR, prices=STAR.prices + (Price(),)),
    ),
    # --- a unit short, one bound at a time ---
    #
    # A star is the pattern to take these apart on, because every one of its
    # bounds has a constant part and a part that grows: the setup charge, the
    # per-position charge, and for the cost the square that the attempts loop
    # puts on top of a loop that is already linear.
    Case(
        "cost-one-unit-short",
        "The setup charge, one unit lower than the register file and the "
        "ovector really cost to zero.",
        "CrTotalCost",
        b"a*",
        less(STAR, "cost", 0),
    ),
    Case(
        "cost-one-unit-short-per-position",
        "The term in n, which is the one that decides whether a long subject "
        "fits the budget.",
        "CrTotalCost",
        b"a*",
        less(STAR, "cost", 1),
    ),
    Case(
        "cost-one-unit-short-in-the-square",
        "And the square, which is a linear loop run from every starting "
        "position and is what dominates any subject worth the name.",
        "CrTotalCost",
        b"a*",
        less(STAR, "cost", 2),
    ),
    Case(
        "stack-one-entry-short",
        "One backtrack entry fewer than the deepest the search goes.",
        "CrTotalStack",
        b"a*",
        less(STAR, "stack", 1),
    ),
    Case(
        "memory-one-byte-short",
        "One IR byte fewer than the peak, which counts the buffer being copied "
        "from as well as the one being copied to.",
        "CrTotalMem",
        b"a*",
        less(STAR, "mem", 0),
    ),
    Case(
        "memory-one-byte-short-per-position",
        "And one byte fewer of the capacity the two growing arrays reach.",
        "CrTotalMem",
        b"a*",
        less(STAR, "mem", 1),
    ),
    Case(
        "region-work-one-visit-short",
        "The root\'s own price, a visit short. A region is checked against what "
        "its children claim, so this fails at the region rather than at the "
        "total it feeds.",
        "CrRegionWork",
        b"a*",
        less(STAR, 0, "work", 1),
    ),
    Case(
        "region-stack-one-entry-short",
        "The repetition pushes one entry per pass through its head, and this "
        "claims it pushes fewer.",
        "CrRegionStack",
        b"a*",
        less(STAR, 2, "stack", 1),
    ),
    Case(
        "region-trail-one-entry-short",
        "Its undo entries, which the counter\'s zeroing, its increment and the "
        "position it remembers all fill.",
        "CrRegionTrail",
        b"a*",
        less(STAR, 2, "trail", 0),
    ),
    Case(
        "region-outs-one-way-short",
        "And its ambiguity, one way out short. Understating that would let "
        "everything after the loop be priced for fewer passes than it gets.",
        "CrRegionOuts",
        b"a*",
        less(STAR, 2, "outs", 1),
    ),
    Case(
        "inner-region-work-one-visit-short",
        "A group three levels down, a visit short, to show that the induction "
        "reaches the leaves rather than stopping at what the root claims.",
        "CrRegionWork",
        b"(ab)*c",
        less(GROUPED, 3, "work", 0),
    ),
    Case(
        "inner-region-trail-one-entry-short",
        "And the two saves that group is there for.",
        "CrRegionTrail",
        b"(ab)*c",
        less(GROUPED, 3, "trail", 0),
    ),
    # --- what the composition rules refuse to price ---
    Case(
        "ambiguity-that-grows-with-the-subject",
        "A star inside a star. The inner one hands the outer one more ways to "
        "match at every extra byte of subject, so the pass count is a power of "
        "a polynomial and no bound of this shape has that form. A refusal is "
        "the honest answer.",
        "CrAmbiguous",
        b"(?:a*)*",
        # The inner loop compiles to the same five instructions a bare star
        # does, so it is priced the same way; the outer one is what has no
        # answer, and it is reached before anything looks at the claims.
        Certificate(prices=(Price(),) * 3 + STAR.prices[1:]),
    ),
    Case(
        "a-pass-count-past-the-counter",
        "Two ways round a loop that may go round sixty times is 2^61, which no "
        "counter holds. The requirement saturating is not a requirement met.",
        "CrOverflow",
        b"(?:a|a){0,60}",
        # Same body as the bounded case above, and the same four regions under
        # the repeat, so the ambiguity is a number and only the count is not.
        Certificate(prices=(Price(),) * 3 + AMBIGUOUS.prices[3:]),
    ),
    # --- a tree that is not a tree ---
    Case(
        "no-regions",
        "A certificate with no root has nothing to be the pattern\'s bound.",
        "CrNoRegions",
        b"abc",
        Certificate(prices=()),
        regions=(),
    ),
    Case(
        "root-is-not-a-root",
        "Region 0 is the root by position, and has to say so as well.",
        "CrRootKind",
        b"abc",
        unpriced(1),
        regions=(region("RkGroup", spec.NONE, 0, 4),),
    ),
    Case(
        "root-has-a-parent",
        "Nothing encloses the whole program.",
        "CrRootParent",
        b"abc",
        unpriced(1),
        regions=(region("RkRoot", 0, 0, 4),),
    ),
    Case(
        "root-starts-late",
        "A root that misses the first instruction prices less than the pattern.",
        "CrRootRange",
        b"abc",
        unpriced(1),
        regions=(region("RkRoot", spec.NONE, 1, 4),),
    ),
    Case(
        "root-stops-early",
        "And a root that stops short of the last one prices less as well.",
        "CrRootRange",
        b"abc",
        unpriced(1),
        regions=(root(3),),
    ),
    Case(
        "two-roots",
        "Only region 0 is the root, or the tree has two places to start from.",
        "CrTwoRoots",
        b"abc",
        unpriced(2),
        regions=(root(4), region("RkRoot", 0, 1, 2)),
    ),
    Case(
        "parent-above-its-child",
        "A parent at or above its child\'s index is what a cycle looks like from "
        "here, and refusing it is what makes the tree a tree without a walk.",
        "CrParentOrder",
        b"abc",
        unpriced(2),
        regions=(root(4), region("RkGroup", 1, 1, 2)),
    ),
    Case(
        "range-runs-backwards",
        "A region that ends before it starts covers no instruction at all.",
        "CrBackwards",
        b"abc",
        unpriced(2),
        regions=(root(4), region("RkGroup", 0, 3, 2)),
    ),
    Case(
        "child-outside-its-parent",
        "A child reaching past its parent would be priced by neither.",
        "CrNotNested",
        b"abc",
        unpriced(2),
        regions=(root(4), region("RkGroup", 0, 1, 5)),
    ),
    Case(
        "child-starts-before-its-parent",
        "The other half of the nesting rule, and the reason it is a refusal of "
        "its own rather than the sibling one: reaching back before the parent "
        "begins is a tree that does not nest, not two children colliding.",
        "CrNotNested",
        b"abc",
        unpriced(3),
        regions=(
            root(4),
            region("RkGroup", 0, 2, 4),
            region("RkBranch", 1, 1, 3),
        ),
    ),
    Case(
        "siblings-overlap",
        "Two children sharing an instruction would have it counted twice, or by "
        "whichever of them the composition rule reached first.",
        "CrOverlap",
        b"abc",
        unpriced(3),
        regions=(root(4), region("RkGroup", 0, 0, 3), region("RkGroup", 0, 2, 4)),
    ),
    Case(
        "siblings-out-of-order",
        "Disjoint but backwards is refused too: the compiler emits regions as it "
        "flattens the AST, so source order costs a correct analyzer nothing and "
        "lets the checker settle both halves of the sibling rule in one pass.",
        "CrOverlap",
        b"abc",
        unpriced(3),
        regions=(root(4), region("RkGroup", 0, 2, 4), region("RkGroup", 0, 0, 2)),
    ),
    Case(
        "a-bound-with-no-base",
        "0^n is 1 at n = 0 and 0 after that. No bound has that shape, and one "
        "that vanishes on longer subjects would look like a bound that holds.",
        "CrBase",
        b"abc",
        claiming(LITERAL, cost=Poly((1,), 0)),
    ),
    Case(
        "a-price-with-no-base",
        "The same rule inside the tree, where the composition rules would go on "
        "to multiply the thing.",
        "CrBase",
        b"abc",
        claiming(
            LITERAL,
            prices=(replace(LITERAL.prices[0], work=Poly((4,), 0)),)
            + LITERAL.prices[1:],
        ),
    ),
    # --- the tree has to account for the code it covers ---
    Case(
        "a-child-that-covers-nothing",
        "A region of zero width prices no instruction and says nothing its "
        "parent does not, so the walk never reaches it and it is left over. "
        "The compiler drops one rather than emitting it, which is why this "
        "tree has to be written by hand.",
        "CrChildren",
        b"abc",
        unpriced(2),
        regions=(root(4), region("RkGroup", 0, 4, 4)),
    ),
    Case(
        "an-alternation-whose-child-is-not-a-branch",
        "The branches of an alternation are what its shape is read off, so a "
        "child of another kind leaves the split arms unaccounted for.",
        "CrChildren",
        b"a|b",
        unpriced(4),
        regions=(
            root(5),
            region("RkAlt", 0, 0, 4),
            region("RkGroup", 1, 1, 2),
            region("RkBranch", 1, 3, 4),
        ),
    ),
    Case(
        "a-branch-outside-an-alternation",
        "A branch is one arm of an alternation and means nothing anywhere "
        "else. The alternation refuses a child that is not a branch; this is "
        "the same rule read from the other end, and between them they say that "
        "the two only ever come in pairs.",
        "CrChildren",
        b"abc",
        unpriced(2),
        regions=(root(4), region("RkBranch", 0, 0, 3)),
    ),
    Case(
        "an-alternation-of-one",
        "One branch is not an alternation: the compiler emits no split for it, "
        "so a region claiming to be one prices instructions that are not there.",
        "CrShape",
        b"a|b",
        unpriced(3),
        regions=(root(5), region("RkAlt", 0, 0, 4), region("RkBranch", 1, 1, 2)),
    ),
    Case(
        "a-branch-that-does-not-follow-its-split",
        "The first branch begins right after the split that guards it. A "
        "region starting anywhere else is not the branch that split leads to.",
        "CrShape",
        b"a|b",
        unpriced(4),
        regions=(
            root(5),
            region("RkAlt", 0, 0, 4),
            region("RkBranch", 1, 2, 2),
            region("RkBranch", 1, 3, 4),
        ),
    ),
    Case(
        "a-repeat-over-code-that-repeats-nothing",
        "Neither an optional item\'s split nor a counted repetition\'s header, so "
        "there is no rule to price it with.",
        "CrShape",
        b"abc",
        unpriced(2),
        regions=(root(4), region("RkRepeat", 0, 0, 3)),
    ),
    Case(
        "a-repeat-that-stops-before-its-tail",
        "The range of a counted repetition ends where the repetition does. One "
        "instruction short of that leaves the tail behind, and the tail is a "
        "repetition opcode no region is left to explain.",
        "CrOpcode",
        b"a*",
        unpriced(2),
        regions=(root(6), region("RkRepeat", 0, 0, 4)),
    ),
    Case(
        "a-repeat-that-reaches-past-its-tail",
        "One instruction the other way is a range whose last instruction is "
        "not a tail at all, which is what ties a repeat region to the entry in "
        "the repetition table.",
        "CrShape",
        b"a*",
        unpriced(2),
        regions=(root(6), region("RkRepeat", 0, 0, 6)),
    ),
]


def _ordinal(enum: str, variant: str) -> int:
    return program().enum_map[enum].ordinal(variant)


def _variant(enum: str, ordinal: int) -> str:
    return program().enum_map[enum].variants[ordinal]


def _poly(p: Poly) -> dict:
    return {"base": p.base, **{f"c{d}": coef(p, d) for d in DEGREES}}


def _read_poly(body: dict) -> Poly:
    return _norm(body["base"], [body[f"c{d}"] for d in DEGREES])


def _region(one: Region) -> dict:
    return {
        "kind": _ordinal("Rk", one.kind),
        "parent": one.parent,
        "lo": one.lo,
        "hi": one.hi,
    }


def _read_region(body: dict) -> Region:
    return Region(
        kind=_variant("Rk", body["kind"]),
        parent=body["parent"],
        lo=body["lo"],
        hi=body["hi"],
    )


def _cert(cert: Certificate) -> dict:
    return {
        "config": _ordinal("Cfg", cert.config),
        "complexity": _ordinal("Cc", cert.complexity),
        "cost": _poly(cert.cost),
        "stack": _poly(cert.stack),
        "mem": _poly(cert.mem),
        "prices": [
            {
                "work": _poly(one.work),
                "outs": _poly(one.outs),
                "stack": _poly(one.stack),
                "trail": _poly(one.trail),
            }
            for one in cert.prices
        ],
    }


def cases() -> list[dict]:
    """Every case, with the verdict and the bounds the reference interpreter gives."""
    out = []
    for case in CASES:
        built = case.subject()
        verdict = ENGINE.check_certificate(built, case.cert, case.config)
        if verdict != case.check:
            raise AssertionError(
                f"{case.name}: the checker says {verdict}, the case says {case.check}"
            )
        entry = {
            "name": case.name,
            "note": case.note,
            "pattern": case.pattern.hex(),
            "config": _ordinal("Cfg", case.config),
            "cert": _cert(case.cert),
            "check": _ordinal("Cr", case.check),
            "bounds": [
                {
                    "n": length,
                    **{
                        key: ENGINE.bound(case.cert, which, length)
                        for key, which in KINDS
                    },
                }
                for length in LENGTHS
            ],
        }
        if case.regions is not None:
            entry["regions"] = [_region(one) for one in case.regions]
        out.append(entry)
    return out


def corpus() -> dict:
    return conformance.document(NOTE, cases())


def corpus_text() -> str:
    return conformance.text(corpus())


def load(path=PATH) -> list[Case]:
    """The committed corpus, decoded back into the cases it was written from.

    The Python runner reads the file the other two read rather than the objects
    it was generated from, so an encoding that lost something fails here
    instead of quietly agreeing with itself.
    """
    out: list[Case] = []
    for entry in conformance.read(path)["cases"]:
        body = entry["cert"]
        held = entry.get("regions")
        out.append(
            Case(
                name=entry["name"],
                note=entry["note"],
                check=_variant("Cr", entry["check"]),
                pattern=bytes.fromhex(entry["pattern"]),
                config=_variant("Cfg", entry["config"]),
                regions=None if held is None else tuple(_read_region(o) for o in held),
                cert=Certificate(
                    prices=tuple(
                        Price(
                            work=_read_poly(one["work"]),
                            outs=_read_poly(one["outs"]),
                            stack=_read_poly(one["stack"]),
                            trail=_read_poly(one["trail"]),
                        )
                        for one in body["prices"]
                    ),
                    cost=_read_poly(body["cost"]),
                    stack=_read_poly(body["stack"]),
                    mem=_read_poly(body["mem"]),
                    config=_variant("Cfg", body["config"]),
                    complexity=_variant("Cc", body["complexity"]),
                ),
                bounds=tuple(entry["bounds"]),
            )
        )
    return out


__all__ = [
    "CASES",
    "KINDS",
    "LENGTHS",
    "PATH",
    "Case",
    "Program",
    "cases",
    "claiming",
    "compiled",
    "const",
    "corpus",
    "corpus_text",
    "less",
    "load",
    "minimal",
    "price",
    "read",
    "region",
    "root",
    "unpriced",
]
