"""What the certificate checker has to answer, in every language.

`certificate.py` is the checker; this is the corpus it is held to. It sits
beside the checker rather than beside the printers, because its subject is the
engine rather than the lowering — the generator reaches across for it the same
way it reaches for the wave 1 restatement in `oracle/conformance.py`.

It exists because a certificate has no way in through the public API, which is
exactly the gap DESIGN.md section 8 asks these corpora to close: without it the
checker would be the one piece of the engine that both backends carried and
neither ran, on the link the design calls tested rather than proved.

The cases are written as the driver's Python values, because those read like
the thing they describe. What goes in the file is enum ordinals and plain
numbers: a runner in another language should not have to know variant names in
order to check a variant.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from ..oracle import conformance
from ..paths import CONFORMANCE_DIR
from ..tir.types import CAP, CEILING
from . import spec
from .driver import Certificate, Engine, Region, Sum, Term
from .program import program

PATH = CONFORMANCE_DIR / "certificates.json"

NOTE = (
    "Generated by pcretruste.engine.certificate_corpus. Each case hands the engine's "
    "bound-certificate checker one certificate and asks for the three bounds it "
    "prices, at every subject length below. Every implementation of the engine has "
    "to give exactly these answers: the same verdict, and the same number or the "
    "same refusal. A bound of null is the ExceedsBudget of DESIGN.md section 2.4, "
    "which is a refusal rather than a number and never a saturated counter."
)

CODE = 6
"""Instructions in the pattern these certificates claim to price."""

LENGTHS = (0, 1, 2, 10, 53, 65535, CAP)
"""Subject lengths every case is evaluated at.

Small ones because that is where a bound is a usable number, 53 because it is
where a doubling term runs out of counter, and the cap because a bound has to
refuse rather than wrap at the far end of the range.
"""

KINDS = (("cost", "BkCost"), ("stack", "BkStack"), ("mem", "BkMem"))
"""What the file calls each bound, and what the engine calls the same one."""


@dataclass(frozen=True)
class Case:
    """One certificate, and the verdict it has to draw.

    The verdict is written down rather than recorded, so a checker that changed
    its mind breaks generation loudly instead of quietly rewriting the file it
    is supposed to be held to. The bounds are recorded, because writing out
    three numbers at seven subject lengths by hand would be transcription
    rather than specification; `tests/test_certificate.py` states the ones
    that say something on their own.
    """

    name: str
    note: str
    check: str
    cert: Certificate
    codelen: int = CODE
    bounds: tuple[dict, ...] = field(default=(), compare=False)
    """What the file records this certificate evaluating to.

    Out of the comparison, so that the round-trip check is about the case and
    not about numbers the case never claimed.
    """


def root(**over) -> Region:
    """The region every certificate needs: the whole program, no parent."""
    return Region(**{"kind": "RkRoot", "parent": spec.NONE, "lo": 0, "hi": CODE, **over})


def priced(*terms: Term, complexity: str = "CcNotProvenLinear", **over) -> Certificate:
    """A root-only certificate whose cost is the sum of these terms."""
    return Certificate(
        regions=(root(cost=Sum(0, len(terms)), **over),),
        terms=terms,
        complexity=complexity,
    )


# --- a well-formed region tree, and every way to fail to be one ---

CASES: list[Case] = [
    Case(
        "root-only",
        "The least a certificate can be: one region over the whole program, "
        "pricing nothing. A region with no terms is a bound of zero rather "
        "than a missing bound.",
        "CrOk",
        Certificate(regions=(root(),)),
    ),
    Case(
        "nested-and-touching",
        "A group holding two alternation branches that meet end to end, with a "
        "quantifier body inside the second of them.",
        "CrOk",
        Certificate(
            regions=(
                root(),
                Region(kind="RkGroup", parent=0, lo=1, hi=5),
                Region(kind="RkBranch", parent=1, lo=1, hi=3),
                Region(kind="RkBranch", parent=1, lo=3, hi=5),
                Region(kind="RkRepeat", parent=3, lo=3, hi=4),
            )
        ),
    ),
    Case(
        "empty-region",
        "A group with nothing in it compiles to two saves and no body between "
        "them, so a region of zero width is a real thing rather than a mistake.",
        "CrOk",
        Certificate(regions=(root(), Region(kind="RkGroup", parent=0, lo=2, hi=2))),
    ),
    Case(
        "no-regions",
        "A certificate with no root has nothing to be the pattern's bound.",
        "CrNoRegions",
        Certificate(regions=()),
    ),
    Case(
        "root-is-not-a-root",
        "Region 0 is the root by position, and has to say so as well.",
        "CrRootKind",
        Certificate(regions=(root(kind="RkGroup"),)),
    ),
    Case(
        "root-has-a-parent",
        "Nothing encloses the whole program.",
        "CrRootParent",
        Certificate(regions=(root(parent=0),)),
    ),
    Case(
        "root-starts-late",
        "A root that misses the first instruction prices less than the pattern.",
        "CrRootRange",
        Certificate(regions=(root(lo=1),)),
    ),
    Case(
        "root-stops-early",
        "And a root that stops short of the last one prices less as well.",
        "CrRootRange",
        Certificate(regions=(root(hi=CODE - 1),)),
    ),
    Case(
        "two-roots",
        "Only region 0 is the root, or the tree has two places to start from.",
        "CrTwoRoots",
        Certificate(regions=(root(), Region(kind="RkRoot", parent=0, lo=1, hi=2))),
    ),
    Case(
        "parent-above-its-child",
        "A parent at or above its child's index is what a cycle looks like from "
        "here, and refusing it is what makes the tree a tree without a walk.",
        "CrParentOrder",
        Certificate(regions=(root(), Region(kind="RkGroup", parent=1, lo=1, hi=2))),
    ),
    Case(
        "range-runs-backwards",
        "A region that ends before it starts covers no instruction at all.",
        "CrBackwards",
        Certificate(regions=(root(), Region(kind="RkGroup", parent=0, lo=3, hi=2))),
    ),
    Case(
        "child-outside-its-parent",
        "A child reaching past its parent would be priced by neither.",
        "CrNotNested",
        Certificate(
            regions=(root(), Region(kind="RkGroup", parent=0, lo=1, hi=CODE + 1))
        ),
    ),
    Case(
        "child-starts-before-its-parent",
        "The other half of the nesting rule, and the reason it is a refusal of "
        "its own rather than the sibling one: reaching back before the parent "
        "begins is a tree that does not nest, not two children colliding.",
        "CrNotNested",
        Certificate(
            regions=(
                root(),
                Region(kind="RkGroup", parent=0, lo=2, hi=5),
                Region(kind="RkBranch", parent=1, lo=1, hi=3),
            )
        ),
    ),
    Case(
        "siblings-overlap",
        "Two children sharing an instruction would have it counted twice, or by "
        "whichever of them the composition rule reached first.",
        "CrOverlap",
        Certificate(
            regions=(
                root(),
                Region(kind="RkBranch", parent=0, lo=0, hi=3),
                Region(kind="RkBranch", parent=0, lo=2, hi=4),
            )
        ),
    ),
    Case(
        "siblings-out-of-order",
        "Disjoint but backwards is refused too: the compiler emits regions as it "
        "flattens the AST, so source order costs a correct analyzer nothing and "
        "lets the checker settle both halves of the sibling rule in one pass.",
        "CrOverlap",
        Certificate(
            regions=(
                root(),
                Region(kind="RkBranch", parent=0, lo=3, hi=CODE),
                Region(kind="RkBranch", parent=0, lo=0, hi=3),
            )
        ),
    ),
    Case(
        "siblings-meet",
        "Meeting end to end is not overlapping, which is the common case.",
        "CrOk",
        Certificate(
            regions=(
                root(),
                Region(kind="RkBranch", parent=0, lo=0, hi=3),
                Region(kind="RkBranch", parent=0, lo=3, hi=CODE),
            )
        ),
    ),
    Case(
        "sum-names-terms-that-are-not-there",
        "An empty term table prices nothing, whatever a region claims.",
        "CrTermRange",
        Certificate(regions=(root(cost=Sum(0, 1)),)),
    ),
    Case(
        "sum-runs-past-the-table",
        "And a sum may not reach past the last term either. Asked for a bound "
        "anyway, the engine answers rather than reading past the end.",
        "CrTermRange",
        Certificate(regions=(root(cost=Sum(3, 2)),), terms=(Term(1),)),
    ),
    Case(
        "term-worth-nothing",
        "A term with no coefficient contributes nothing, so it says nothing that "
        "an empty sum does not say more clearly — and it would make every rule "
        "below conditional on a coefficient.",
        "CrZeroTerm",
        priced(Term(0, base=2)),
    ),
    Case(
        "base-of-zero",
        "0^n is 1 at n = 0 and 0 after that. No bound has that shape, and one "
        "that vanishes on longer subjects would look like a bound that holds.",
        "CrBase",
        priced(Term(1, base=0)),
    ),
    Case(
        "degree-past-the-cap",
        "A power the soundness argument has no rule for.",
        "CrDegree",
        priced(Term(1, degree=spec.MAX_DEGREE + 1)),
    ),
    Case(
        "linear-claim-with-a-growing-base",
        "Linear means c * (n + 1). An exponential term is not that.",
        "CrNotLinear",
        priced(Term(1, base=2), complexity="CcLinear"),
    ),
    Case(
        "linear-claim-with-a-square",
        "Nor is a square, however modest its coefficient.",
        "CrNotLinear",
        priced(Term(1, degree=2), complexity="CcLinear"),
    ),
    Case(
        "linear-claim-that-holds",
        "The Pike bound of DESIGN.md section 5: a constant and a term in n.",
        "CrOk",
        priced(Term(17), Term(17, degree=1), complexity="CcLinear"),
    ),
    # --- and what the arithmetic answers ---
    Case(
        "polynomial",
        "3 + 2n + n^2, evaluated left to right in counter arithmetic.",
        "CrOk",
        priced(Term(3), Term(2, degree=1), Term(1, degree=2)),
    ),
    Case(
        "exponential",
        "2^n is a number until it is not, which happens at n = 53.",
        "CrOk",
        priced(Term(1, base=2)),
    ),
    Case(
        "at-the-saturation-point",
        "Exactly 2^53 - 1 is a bound a caller can pass back as a cost limit.",
        "CrOk",
        priced(Term(CAP)),
    ),
    Case(
        "one-past-the-saturation-point",
        "One more is not, and comes back as a refusal rather than as the cap.",
        "CrOk",
        priced(Term(CAP), Term(1)),
    ),
    Case(
        "product-that-would-saturate",
        "The pre-check is on the operands, so the product never happens.",
        "CrOk",
        priced(Term(CAP, degree=1)),
    ),
    Case(
        "product-that-just-fits",
        "And the one below it is exact.",
        "CrOk",
        priced(Term(CAP // 2, degree=1)),
    ),
    Case(
        "at-the-stack-ceiling",
        "The largest stack bound a stack limit could name.",
        "CrOk",
        priced(Term(spec.MAX_STACK), stack=Sum(0, 1), mem=Sum(0, 1)),
    ),
    Case(
        "past-the-stack-ceiling",
        "One entry more, which no limit could accept, so it is not a number.",
        "CrOk",
        priced(Term(spec.MAX_STACK + 1), stack=Sum(0, 1), mem=Sum(0, 1)),
    ),
    Case(
        "at-the-memory-ceiling",
        "The section 3 byte ceiling, which is the largest reservation there is.",
        "CrOk",
        priced(Term(CEILING), stack=Sum(0, 1), mem=Sum(0, 1)),
    ),
    Case(
        "past-the-memory-ceiling",
        "One byte more is refused as memory and still fine as cost, which is the "
        "whole difference between the three projections.",
        "CrOk",
        priced(Term(CEILING + 1), stack=Sum(0, 1), mem=Sum(0, 1)),
    ),
    Case(
        "children-are-not-summed-behind-the-accessor",
        "The pattern's bound is the root's bound. Nothing adds the children in, "
        "because the composition rule that would justify it does not exist yet.",
        "CrOk",
        Certificate(
            regions=(
                root(cost=Sum(0, 1)),
                Region(kind="RkGroup", parent=0, lo=1, hi=2, cost=Sum(1, 1)),
            ),
            terms=(Term(7), Term(1000)),
        ),
    ),
]


def _ordinal(enum: str, variant: str) -> int:
    return program().enum_map[enum].ordinal(variant)


def _variant(enum: str, ordinal: int) -> str:
    return program().enum_map[enum].variants[ordinal]


def _sum(one: Sum) -> dict:
    return {"first": one.first, "count": one.count}


def _cert(cert: Certificate) -> dict:
    return {
        "config": _ordinal("Cfg", cert.config),
        "complexity": _ordinal("Cc", cert.complexity),
        "regions": [
            {
                "kind": _ordinal("Rk", region.kind),
                "parent": region.parent,
                "lo": region.lo,
                "hi": region.hi,
                "cost": _sum(region.cost),
                "stack": _sum(region.stack),
                "mem": _sum(region.mem),
            }
            for region in cert.regions
        ],
        "terms": [
            {"coef": one.coef, "base": one.base, "degree": one.degree}
            for one in cert.terms
        ],
    }


def cases() -> list[dict]:
    """Every case, with the verdict and the bounds the reference interpreter gives."""
    engine = Engine()
    out = []
    for case in CASES:
        verdict = engine.check_certificate(case.cert, case.codelen)
        if verdict != case.check:
            raise AssertionError(
                f"{case.name}: the checker says {verdict}, the case says {case.check}"
            )
        entry = {
            "name": case.name,
            "note": case.note,
            "codelen": case.codelen,
            "cert": _cert(case.cert),
            "check": _ordinal("Cr", case.check),
            "bounds": [
                {
                    "n": length,
                    **{key: engine.bound(case.cert, which, length) for key, which in KINDS},
                }
                for length in LENGTHS
            ],
        }
        out.append(entry)
    return out


def corpus() -> dict:
    return conformance.document(NOTE, cases())


def corpus_text() -> str:
    return conformance.text(corpus())


def load(path=PATH) -> list[Case]:
    """The committed corpus, decoded back into the cases it was written from.

    The Python runner reads the file the other two read rather than the objects
    it was generated from, so an encoding that lost something fails here
    instead of quietly agreeing with itself.
    """
    cases: list[Case] = []
    for entry in conformance.read(path)["cases"]:
        body = entry["cert"]
        cases.append(
            Case(
                name=entry["name"],
                note=entry["note"],
                check=_variant("Cr", entry["check"]),
                cert=Certificate(
                    regions=tuple(
                        Region(
                            kind=_variant("Rk", one["kind"]),
                            parent=one["parent"],
                            lo=one["lo"],
                            hi=one["hi"],
                            cost=Sum(**one["cost"]),
                            stack=Sum(**one["stack"]),
                            mem=Sum(**one["mem"]),
                        )
                        for one in body["regions"]
                    ),
                    terms=tuple(Term(**one) for one in body["terms"]),
                    config=_variant("Cfg", body["config"]),
                    complexity=_variant("Cc", body["complexity"]),
                ),
                codelen=entry["codelen"],
                bounds=tuple(entry["bounds"]),
            )
        )
    return cases


__all__ = [
    "CASES",
    "CODE",
    "KINDS",
    "PATH",
    "Case",
    "cases",
    "corpus",
    "corpus_text",
    "load",
    "priced",
    "root",
]
