"""The certificate corpus: what the checker has to answer, in every language.

The checker is engine code, so both backends already carry it. Nothing ran it
there, though, because the wave 1 corpus only ever reaches compilation and
matching, and a certificate has no way in through the public API — which is
exactly the gap DESIGN.md section 8 asks these corpora to close, since the
printing step is a tested link rather than a proved one.

So this is the way in: a list of certificates, the verdict each one has to
draw, and the bounds each one has to evaluate to, computed once through the
reference interpreter and then answered identically by the generated Go and
JavaScript. The Go runner sits inside the generated package, because Go cannot
reach a lower-case struct field from outside one and TIR field names are
printed verbatim; the JavaScript runner needs no such thing.

The cases are written as the driver's Python values, because those read like
the thing they describe. What goes in the file is enum ordinals and plain
numbers: a runner in another language should not have to know variant names in
order to check a variant.
"""

from __future__ import annotations

from dataclasses import dataclass

from ..engine import Certificate, Engine, Region, Sum, Term, spec
from ..engine.program import program
from ..oracle import conformance
from ..paths import CONFORMANCE_DIR
from ..tir.types import CAP, CEILING

PATH = CONFORMANCE_DIR / "certificates.json"

NOTE = (
    "Generated by pcretruste.backends.certificates. Each case hands the engine's "
    "bound-certificate checker one certificate and asks for the three bounds it "
    "prices, at every subject length below. Every implementation of the engine has "
    "to give exactly these answers: the same verdict, and the same number or the "
    "same refusal. A bound of null is the ExceedsBudget of DESIGN.md section 2.4, "
    "which is a refusal rather than a number and never a saturated counter."
)

CODE = 6
"""Instructions in the pattern these certificates claim to price."""

LENGTHS = (0, 1, 2, 10, 53, 65535, CAP)
"""Subject lengths every case is evaluated at.

Small ones because that is where a bound is a usable number, 53 because it is
where a doubling term runs out of counter, and the cap because a bound has to
refuse rather than wrap at the far end of the range.
"""

KINDS = ("cost", "stack", "mem")


@dataclass(frozen=True)
class Case:
    """One certificate, and the verdict it has to draw.

    The verdict is written down rather than recorded, so a checker that changed
    its mind breaks generation loudly instead of quietly rewriting the file it
    is supposed to be held to. The bounds are recorded, because writing out
    three numbers at seven subject lengths by hand would be transcription
    rather than specification; `tests/test_certificate.py` states the ones
    that say something on their own.
    """

    name: str
    note: str
    check: str
    cert: Certificate
    codelen: int = CODE


def root(**over) -> Region:
    """The region every certificate needs: the whole program, no parent."""
    return Region(**{"kind": "RkRoot", "parent": spec.NONE, "lo": 0, "hi": CODE, **over})


def priced(*terms: Term, complexity: str = "CcNotProvenLinear", **over) -> Certificate:
    """A root-only certificate whose cost is the sum of these terms."""
    return Certificate(
        regions=(root(cost=Sum(0, len(terms)), **over),),
        terms=terms,
        complexity=complexity,
    )


def _alike(coef: int) -> Certificate:
    """One term, priced as all three quantities at once, so the ceilings differ."""
    return Certificate(
        regions=(root(cost=Sum(0, 1), stack=Sum(0, 1), mem=Sum(0, 1)),),
        terms=(Term(coef),),
    )


# --- a well-formed region tree, and every way to fail to be one ---

CASES: list[Case] = [
    Case(
        "root-only",
        "The least a certificate can be: one region over the whole program.",
        "CrOk",
        Certificate(regions=(root(),)),
    ),
    Case(
        "nested-and-touching",
        "A group holding two alternation branches that meet end to end, with a "
        "quantifier body inside the second of them.",
        "CrOk",
        Certificate(
            regions=(
                root(),
                Region(kind="RkGroup", parent=0, lo=1, hi=5),
                Region(kind="RkBranch", parent=1, lo=1, hi=3),
                Region(kind="RkBranch", parent=1, lo=3, hi=5),
                Region(kind="RkRepeat", parent=3, lo=3, hi=4),
            )
        ),
    ),
    Case(
        "empty-region",
        "A group with nothing in it compiles to two saves and no body between "
        "them, so a region of zero width is a real thing rather than a mistake.",
        "CrOk",
        Certificate(regions=(root(), Region(kind="RkGroup", parent=0, lo=2, hi=2))),
    ),
    Case(
        "no-regions",
        "A certificate with no root has nothing to be the pattern's bound.",
        "CrNoRegions",
        Certificate(regions=()),
    ),
    Case(
        "root-is-not-a-root",
        "Region 0 is the root by position, and has to say so as well.",
        "CrRootKind",
        Certificate(regions=(root(kind="RkGroup"),)),
    ),
    Case(
        "root-has-a-parent",
        "Nothing encloses the whole program.",
        "CrRootParent",
        Certificate(regions=(root(parent=0),)),
    ),
    Case(
        "root-starts-late",
        "A root that misses the first instruction prices less than the pattern.",
        "CrRootRange",
        Certificate(regions=(root(lo=1),)),
    ),
    Case(
        "root-stops-early",
        "And a root that stops short of the last one prices less as well.",
        "CrRootRange",
        Certificate(regions=(root(hi=CODE - 1),)),
    ),
    Case(
        "two-roots",
        "Only region 0 is the root, or the tree has two places to start from.",
        "CrTwoRoots",
        Certificate(regions=(root(), Region(kind="RkRoot", parent=0, lo=1, hi=2))),
    ),
    Case(
        "parent-above-its-child",
        "A parent at or above its child's index is what a cycle looks like from "
        "here, and refusing it is what makes the tree a tree without a walk.",
        "CrParentOrder",
        Certificate(regions=(root(), Region(kind="RkGroup", parent=1, lo=1, hi=2))),
    ),
    Case(
        "range-runs-backwards",
        "A region that ends before it starts covers no instruction at all.",
        "CrBackwards",
        Certificate(regions=(root(), Region(kind="RkGroup", parent=0, lo=3, hi=2))),
    ),
    Case(
        "child-outside-its-parent",
        "A child reaching past its parent would be priced by neither.",
        "CrNotNested",
        Certificate(
            regions=(root(), Region(kind="RkGroup", parent=0, lo=1, hi=CODE + 1))
        ),
    ),
    Case(
        "siblings-overlap",
        "Two children sharing an instruction would have it counted twice, or by "
        "whichever of them the composition rule reached first.",
        "CrOverlap",
        Certificate(
            regions=(
                root(),
                Region(kind="RkBranch", parent=0, lo=0, hi=3),
                Region(kind="RkBranch", parent=0, lo=2, hi=4),
            )
        ),
    ),
    Case(
        "siblings-out-of-order",
        "Disjoint but backwards is refused too: the compiler emits regions as it "
        "flattens the AST, so source order costs a correct analyzer nothing and "
        "lets the checker settle both halves of the sibling rule in one pass.",
        "CrOverlap",
        Certificate(
            regions=(
                root(),
                Region(kind="RkBranch", parent=0, lo=3, hi=CODE),
                Region(kind="RkBranch", parent=0, lo=0, hi=3),
            )
        ),
    ),
    Case(
        "siblings-meet",
        "Meeting end to end is not overlapping, which is the common case.",
        "CrOk",
        Certificate(
            regions=(
                root(),
                Region(kind="RkBranch", parent=0, lo=0, hi=3),
                Region(kind="RkBranch", parent=0, lo=3, hi=CODE),
            )
        ),
    ),
    Case(
        "sum-names-terms-that-are-not-there",
        "An empty term table prices nothing, whatever a region claims.",
        "CrTermRange",
        Certificate(regions=(root(cost=Sum(0, 1)),)),
    ),
    Case(
        "sum-runs-past-the-table",
        "And a sum may not reach past the last term either. Asked for a bound "
        "anyway, the engine answers rather than reading past the end.",
        "CrTermRange",
        Certificate(regions=(root(cost=Sum(3, 2)),), terms=(Term(1),)),
    ),
    Case(
        "term-worth-nothing",
        "A term with no coefficient contributes nothing, so it says nothing that "
        "an empty sum does not say more clearly — and it would make every rule "
        "below conditional on a coefficient.",
        "CrZeroTerm",
        priced(Term(0, base=2)),
    ),
    Case(
        "base-of-zero",
        "0^n is 1 at n = 0 and 0 after that. No bound has that shape, and one "
        "that vanishes on longer subjects would look like a bound that holds.",
        "CrBase",
        priced(Term(1, base=0)),
    ),
    Case(
        "degree-past-the-cap",
        "A power the soundness argument has no rule for.",
        "CrDegree",
        priced(Term(1, degree=spec.MAX_DEGREE + 1)),
    ),
    Case(
        "linear-claim-with-a-growing-base",
        "Linear means c * (n + 1). An exponential term is not that.",
        "CrNotLinear",
        priced(Term(1, base=2), complexity="CcLinear"),
    ),
    Case(
        "linear-claim-with-a-square",
        "Nor is a square, however modest its coefficient.",
        "CrNotLinear",
        priced(Term(1, degree=2), complexity="CcLinear"),
    ),
    Case(
        "linear-claim-that-holds",
        "The Pike bound of DESIGN.md section 5: a constant and a term in n.",
        "CrOk",
        priced(Term(17), Term(17, degree=1), complexity="CcLinear"),
    ),
    # --- and what the arithmetic answers ---
    Case(
        "polynomial",
        "3 + 2n + n^2, evaluated left to right in counter arithmetic.",
        "CrOk",
        priced(Term(3), Term(2, degree=1), Term(1, degree=2)),
    ),
    Case(
        "nothing-priced",
        "A region with no terms is a bound of zero, not a missing bound.",
        "CrOk",
        Certificate(regions=(root(),)),
    ),
    Case(
        "exponential",
        "2^n is a number until it is not, which happens at n = 53.",
        "CrOk",
        priced(Term(1, base=2)),
    ),
    Case(
        "at-the-saturation-point",
        "Exactly 2^53 - 1 is a bound a caller can pass back as a cost limit.",
        "CrOk",
        priced(Term(CAP)),
    ),
    Case(
        "one-past-the-saturation-point",
        "One more is not, and comes back as a refusal rather than as the cap.",
        "CrOk",
        priced(Term(CAP), Term(1)),
    ),
    Case(
        "product-that-would-saturate",
        "The pre-check is on the operands, so the product never happens.",
        "CrOk",
        priced(Term(CAP, degree=1)),
    ),
    Case(
        "product-that-just-fits",
        "And the one below it is exact.",
        "CrOk",
        priced(Term(CAP // 2, degree=1)),
    ),
    Case(
        "at-the-stack-ceiling",
        "The largest stack bound a stack limit could name.",
        "CrOk",
        _alike(spec.MAX_STACK),
    ),
    Case(
        "past-the-stack-ceiling",
        "One entry more, which no limit could accept, so it is not a number.",
        "CrOk",
        _alike(spec.MAX_STACK + 1),
    ),
    Case(
        "at-the-memory-ceiling",
        "The section 3 byte ceiling, which is the largest reservation there is.",
        "CrOk",
        _alike(CEILING),
    ),
    Case(
        "past-the-memory-ceiling",
        "One byte more is refused as memory and still fine as cost, which is the "
        "whole difference between the three projections.",
        "CrOk",
        _alike(CEILING + 1),
    ),
    Case(
        "children-are-not-summed-behind-the-accessor",
        "The pattern's bound is the root's bound. Nothing adds the children in, "
        "because the composition rule that would justify it does not exist yet.",
        "CrOk",
        Certificate(
            regions=(
                root(cost=Sum(0, 1)),
                Region(kind="RkGroup", parent=0, lo=1, hi=2, cost=Sum(1, 1)),
            ),
            terms=(Term(7), Term(1000)),
        ),
    ),
]


def _ordinal(enum: str, variant: str) -> int:
    return program().enum_map[enum].ordinal(variant)


def _variant(enum: str, ordinal: int) -> str:
    return program().enum_map[enum].variants[ordinal]


def _sum(one: Sum) -> dict:
    return {"first": one.first, "count": one.count}


def _cert(cert: Certificate) -> dict:
    return {
        "config": _ordinal("Cfg", cert.config),
        "complexity": _ordinal("Cc", cert.complexity),
        "regions": [
            {
                "kind": _ordinal("Rk", region.kind),
                "parent": region.parent,
                "lo": region.lo,
                "hi": region.hi,
                "cost": _sum(region.cost),
                "stack": _sum(region.stack),
                "mem": _sum(region.mem),
            }
            for region in cert.regions
        ],
        "terms": [
            {"coef": one.coef, "base": one.base, "degree": one.degree}
            for one in cert.terms
        ],
    }


def cases() -> list[dict]:
    """Every case, with the verdict and the bounds the reference interpreter gives."""
    engine = Engine()
    out = []
    for case in CASES:
        verdict = engine.check_certificate(case.cert, case.codelen)
        if verdict != case.check:
            raise AssertionError(
                f"{case.name}: the checker says {verdict}, the case says {case.check}"
            )
        entry = {
            "name": case.name,
            "note": case.note,
            "codelen": case.codelen,
            "cert": _cert(case.cert),
            "check": _ordinal("Cr", case.check),
            "bounds": [
                {
                    "n": length,
                    **{
                        kind: engine.bound(case.cert, "Bk" + kind.capitalize(), length)
                        for kind in KINDS
                    },
                }
                for length in LENGTHS
            ],
        }
        out.append(entry)
    return out


def corpus() -> dict:
    return conformance.document(NOTE, cases())


def corpus_text() -> str:
    return conformance.text(corpus())


def load(path=PATH) -> tuple[list[Case], dict[str, list[dict]]]:
    """The committed corpus, decoded back into the cases it was written from.

    The Python runner reads the file the other two read rather than the objects
    it was generated from, so an encoding that lost something would fail here
    instead of quietly agreeing with itself. The bounds come back beside the
    cases, keyed by name, because they are what the file records rather than
    part of what a case says.
    """
    cases: list[Case] = []
    bounds: dict[str, list[dict]] = {}
    for entry in conformance.read(path)["cases"]:
        body = entry["cert"]
        cases.append(
            Case(
                name=entry["name"],
                note=entry["note"],
                check=_variant("Cr", entry["check"]),
                cert=Certificate(
                    regions=tuple(
                        Region(
                            kind=_variant("Rk", one["kind"]),
                            parent=one["parent"],
                            lo=one["lo"],
                            hi=one["hi"],
                            cost=Sum(**one["cost"]),
                            stack=Sum(**one["stack"]),
                            mem=Sum(**one["mem"]),
                        )
                        for one in body["regions"]
                    ),
                    terms=tuple(Term(**one) for one in body["terms"]),
                    config=_variant("Cfg", body["config"]),
                    complexity=_variant("Cc", body["complexity"]),
                ),
                codelen=entry["codelen"],
            )
        )
        bounds[entry["name"]] = entry["bounds"]
    return cases, bounds


__all__ = [
    "CASES",
    "KINDS",
    "LENGTHS",
    "NOTE",
    "PATH",
    "Case",
    "cases",
    "corpus",
    "corpus_text",
    "load",
]
