"""The lowering probe: a small TIR program aimed at what the printers can get wrong.

The engine and its 264-case corpus exercise the backends broadly, but not
squarely. Every multiplication the engine performs is on small offsets, so a
JavaScript printer that forgot `Math.imul` would pass the whole corpus and then
be wrong the first time a product went past 2^53. The same goes for a struct
read that aliases where it should copy, a growth schedule that rounds
differently, and a coercion applied to the wrong operand.

So this program does those things on purpose, with operands chosen to sit on
the boundary, and the conformance corpus of DESIGN.md section 8 carries the
answers. One entry point keeps the runner in each language down to a single
call:

    probe(kind, a, b) -> counter

`kind` picks the operation, `a` and `b` are the operands as counters, and the
answer comes back as a counter — through a cast to u32 where the bit pattern
is what matters, and packed two-at-a-time by `shape` where a branch has a
pair to report.
"""

from __future__ import annotations

import functools
from collections.abc import Callable

from ..dsl import (
    Expr,
    FuncBuilder,
    Module,
    boolean,
    bytes_,
    counter,
    frozen,
    i32,
    inout,
    land,
    u8,
    u32,
    vec,
)
from ..dsl.builder import EnumRef, StructRef
from ..oracle import conformance
from ..paths import CONFORMANCE_DIR
from ..tir import ir
from ..tir.types import CAP

PATH = CONFORMANCE_DIR / "lowering.json"

NOTE = (
    "Generated by pcretruste.backends.lowering. Each case runs probe(kind, a, b) "
    "and every implementation of the probe must answer exactly this. The operands "
    "sit on the boundaries the printers can fall off: the 32-bit widths, the sign "
    "changes, the products that need more than 53 bits to be exact, and the "
    "capacities the growth schedule pins. A branch with a pair to report packs "
    "it into one counter, high half first; shift says by how much, for whoever "
    "is reading a failure rather than running one."
)

TABLE = bytes(range(16, 32))
"""A frozen constant to index, since that is how the engine reads every table."""

# Scalar constants near the top of their range, so that arithmetic on them
# leaves it. Go emits each with its `const` keyword, which is what makes a use
# of one a constant expression that has to be guarded.
BIG_U32 = 4_000_000_007
BIG_I32 = -2_000_000_009
MIN_I32 = -(2**31)
BIG_U8 = 200

SHIFT = 24
"""How far `shape` moves its high half.

Both halves stay under 2^24 for every case the corpus asks, so the packing is
reversible and never reaches the counter's saturation point. That matters: a
saturated answer would still be the same in every language, but it would stop
saying which half went wrong.
"""


class Probe:
    """What every branch has to hand: the operands in each width, and the types."""

    def __init__(
        self,
        f: FuncBuilder,
        pair: StructRef,
        nest: StructRef,
        colour: EnumRef,
        table: Expr,
        scalars: dict[str, Expr],
    ) -> None:
        self.Pair = pair
        self.Nest = nest
        self.Colour = colour
        self.table = table
        self.BIGU = scalars["BIGU"]
        self.BIGI = scalars["BIGI"]
        self.MINI = scalars["MINI"]
        self.BIGB = scalars["BIGB"]
        self.BIGC = scalars["BIGC"]
        self.au = f.let("au", u32, f["a"].cast(u32))
        self.bu = f.let("bu", u32, f["b"].cast(u32))
        self.ai = f.let("ai", i32, f["a"].cast(i32))
        self.bi = f.let("bi", i32, f["b"].cast(i32))
        self.a8 = f.let("a8", u8, f["a"].cast(u8))
        self.b8 = f.let("b8", u8, f["b"].cast(u8))
        self.a = f["a"]
        self.b = f["b"]


def shape(high: Expr, low: Expr) -> Expr:
    """Two u32 answers packed into one counter."""
    return high.cast(counter) * counter(1 << SHIFT) + low.cast(counter)


Branch = Callable[[FuncBuilder, Probe], None]

Operands = list[tuple[int, int]]

BRANCHES: list[tuple[str, Branch, Operands]] = []


def branch(name: str, operands: Operands | None = None) -> Callable[[Branch], Branch]:
    """Register a branch and the operands it is asked about.

    The operands live on the decorator rather than in a table keyed by name,
    so renaming a branch cannot silently give it somebody else's numbers.
    """

    def register(emit: Branch) -> Branch:
        BRANCHES.append((name, emit, SMALLS if operands is None else operands))
        return emit

    return register


def kinds() -> dict[str, int]:
    """Every branch name and the number that selects it."""
    return {name: index for index, (name, _, _) in enumerate(BRANCHES)}


# --- the operands each branch is asked about ---
#
# Chosen to sit on the boundaries rather than in the middle: the widths, the
# sign changes, and the two products whose exact value needs more than 53 bits.

WORD = (0, 1, 255, 65537, 123456789, 0x7FFFFFFF, 0x80000000, 0xFFFFFFFF)

COUNTERS = (0, 1, 2, 3, 94906265, 94906266, 3002399751580331, CAP - 1, CAP)

SMALL = (0, 1, 2, 3, 7, 40, 777, 65535, 1 << 23)

SIZES = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 16, 17, 32, 39, 40)


def _pairs(left: tuple[int, ...], right: tuple[int, ...]) -> Operands:
    return [(a, b) for a in left for b in right]


WORDS = _pairs(WORD, WORD)
COUNTS = _pairs(COUNTERS, COUNTERS)
SMALLS = _pairs(SMALL, SMALL)
ONE_COUNTER = [(a, 0) for a in COUNTERS + WORD]
ONE_SIZE = [(a, 0) for a in SIZES]
NO_OPERANDS = [(0, 0)]
"""For a branch whose answer is a constant: asking twice would say nothing."""


# --- 32-bit arithmetic, where a naive JavaScript product loses low bits ---


@branch("u32-mul", WORDS)
def _u32_mul(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.au * x.bu).cast(counter))


@branch("u32-add", WORDS)
def _u32_add(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.au + x.bu).cast(counter))


@branch("u32-sub", WORDS)
def _u32_sub(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.au - x.bu).cast(counter))


@branch("u32-and", WORDS)
def _u32_and(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.au & x.bu).cast(counter))


@branch("u32-or", WORDS)
def _u32_or(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.au | x.bu).cast(counter))


@branch("u32-xor", WORDS)
def _u32_xor(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.au ^ x.bu).cast(counter))


@branch("u32-neg", WORDS)
def _u32_neg(f: FuncBuilder, x: Probe) -> None:
    f.ret((-x.au).cast(counter))


@branch("u32-bnot", WORDS)
def _u32_bnot(f: FuncBuilder, x: Probe) -> None:
    f.ret((~x.au).cast(counter))


@branch("u32-shl", WORDS)
def _u32_shl(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.au.shl(17).cast(counter))


@branch("u32-shr", WORDS)
def _u32_shr(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.au.shr(17).cast(counter))


@branch("u32-div", WORDS)
def _u32_div(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.au.div(x.bu, u32(4242)).cast(counter))


@branch("u32-rem", WORDS)
def _u32_rem(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.au.rem(x.bu, u32(4242)).cast(counter))


# --- i32, where the sign and the two division corners are the question ---


@branch("i32-mul", WORDS)
def _i32_mul(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.ai * x.bi).cast(u32).cast(counter))


@branch("i32-add", WORDS)
def _i32_add(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.ai + x.bi).cast(u32).cast(counter))


@branch("i32-sub", WORDS)
def _i32_sub(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.ai - x.bi).cast(u32).cast(counter))


@branch("i32-neg", WORDS)
def _i32_neg(f: FuncBuilder, x: Probe) -> None:
    f.ret((-x.ai).cast(u32).cast(counter))


@branch("i32-sar", WORDS)
def _i32_sar(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.ai.sar(5).cast(u32).cast(counter))


@branch("i32-shl", WORDS)
def _i32_shl(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.ai.shl(5).cast(u32).cast(counter))


@branch("i32-div", WORDS)
def _i32_div(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.ai.div(x.bi, i32(-4242)).cast(u32).cast(counter))


@branch("i32-rem", WORDS)
def _i32_rem(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.ai.rem(x.bi, i32(-4242)).cast(u32).cast(counter))


# --- u8, which JavaScript has to mask and Go gets for free ---


@branch("u8-mul", WORDS)
def _u8_mul(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.a8 * x.b8).cast(counter))


@branch("u8-add", WORDS)
def _u8_add(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.a8 + x.b8).cast(counter))


@branch("u8-sub", WORDS)
def _u8_sub(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.a8 - x.b8).cast(counter))


@branch("u8-neg", WORDS)
def _u8_neg(f: FuncBuilder, x: Probe) -> None:
    f.ret((-x.a8).cast(counter))


@branch("u8-bnot", WORDS)
def _u8_bnot(f: FuncBuilder, x: Probe) -> None:
    f.ret((~x.a8).cast(counter))


@branch("u8-shl", WORDS)
def _u8_shl(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.a8.shl(5).cast(counter))


@branch("u8-shr", WORDS)
def _u8_shr(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.a8.shr(3).cast(counter))


# --- counter, which saturates on a pre-check rather than a clamp ---


@branch("counter-add", COUNTS)
def _counter_add(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.a + x.b)


@branch("counter-sub", COUNTS)
def _counter_sub(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.a - x.b)


@branch("counter-mul", COUNTS)
def _counter_mul(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.a * x.b)


@branch("counter-div", COUNTS)
def _counter_div(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.a.div(x.b, counter(4242)))


@branch("counter-rem", COUNTS)
def _counter_rem(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.a.rem(x.b, counter(4242)))


# --- casts, one row of the section 6.13 table each ---


@branch("cast-counter-u8", ONE_COUNTER)
def _cast_counter_u8(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.a.cast(u8).cast(counter))


@branch("cast-counter-u32", ONE_COUNTER)
def _cast_counter_u32(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.a.cast(u32).cast(counter))


@branch("cast-counter-i32", ONE_COUNTER)
def _cast_counter_i32(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.a.cast(i32).cast(u32).cast(counter))


@branch("cast-i32-counter", ONE_COUNTER)
def _cast_i32_counter(f: FuncBuilder, x: Probe) -> None:
    # The one cast that saturates rather than reinterpreting: a count has no
    # negative reading.
    f.ret(x.ai.cast(counter))


@branch("cast-i32-u8", ONE_COUNTER)
def _cast_i32_u8(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.ai.cast(u8).cast(counter))


@branch("cast-bool-counter", WORDS)
def _cast_bool_counter(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.au < x.bu).cast(counter))


# --- sequences: the growth schedule of section 11, read back through cap ---


@branch("push-capacity", ONE_SIZE)
def _push_capacity(f: FuncBuilder, x: Probe) -> None:
    bag = f.let("push_bag", vec(u32, 40))
    i = f.let("push_i", u32, u32(0))
    with f.while_(i < x.au, (x.au - i).cast(counter)):
        f.push(bag, i)
        f.set(i, i + u32(1))
    f.ret(shape(bag.cap(), bag.len()))


@branch("reserve-then-push", _pairs(SIZES, SIZES))
def _reserve_then_push(f: FuncBuilder, x: Probe) -> None:
    bag = f.let("res_bag", vec(u32, 40))
    f.reserve(bag, x.bu)
    i = f.let("res_i", u32, u32(0))
    with f.while_(i < x.au, (x.au - i).cast(counter)):
        f.push(bag, i)
        f.set(i, i + u32(1))
    f.ret(shape(bag.cap(), bag.len()))


@branch("truncate-keeps-capacity", [(a, b) for a in SIZES for b in SIZES if b <= a])
def _truncate_keeps_capacity(f: FuncBuilder, x: Probe) -> None:
    bag = f.let("trunc_bag", vec(u32, 40))
    i = f.let("trunc_i", u32, u32(0))
    with f.while_(i < x.au, (x.au - i).cast(counter)):
        f.push(bag, i)
        f.set(i, i + u32(1))
    f.truncate(bag, x.bu)
    f.ret(shape(bag.cap(), bag.len()))


@branch("pop-gives-the-last", [(a, 0) for a in SIZES if a >= 1])
def _pop_gives_the_last(f: FuncBuilder, x: Probe) -> None:
    bag = f.let("pop_bag", vec(u32, 40))
    i = f.let("pop_i", u32, u32(0))
    with f.while_(i < x.au, (x.au - i).cast(counter)):
        f.push(bag, i + u32(100))
        f.set(i, i + u32(1))
    last = f.let("pop_last", u32, u32(0))
    f.pop(bag, last)
    f.ret(shape(last, bag.len()))


@branch("copy-is-deep")
def _copy_is_deep(f: FuncBuilder, x: Probe) -> None:
    original = f.let("copy_from", vec(u32, 40))
    f.push(original, x.au)
    f.push(original, x.bu)
    duplicate = f.let("copy_to", vec(u32, 40))
    f.copy(duplicate, original)
    f.set(original.at(u32(0)), u32(777))
    # A copy has capacity equal to its length, whatever the original's was.
    f.ret(shape(duplicate.at(u32(0)), duplicate.cap()))


@branch("freeze-empties-the-source")
def _freeze_empties_the_source(f: FuncBuilder, x: Probe) -> None:
    original = f.let("freeze_from", vec(u32, 40))
    f.push(original, x.au)
    kept = f.let("freeze_to", frozen(vec(u32, 40)))
    f.freeze(kept, original)
    f.ret(shape(kept.at(u32(0)), original.len()))


@branch("table-lookup", [(a, 0) for a in WORD + SIZES])
def _table_lookup(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.table.at(x.au & u32(15)).cast(counter))


@branch("and-short-circuits", ONE_SIZE)
def _and_short_circuits(f: FuncBuilder, x: Probe) -> None:
    # The right operand indexes past the end whenever the left is false, so an
    # implementation that evaluates both traps instead of answering.
    bag = f.let("sc_bag", vec(u32, 40))
    f.push(bag, u32(7))
    f.ret(land(x.au < bag.len(), bag.at(x.au) == u32(7)).cast(counter))


# --- structs, which JavaScript would alias where Go copies ---


@branch("struct-read-copies")
def _struct_read_copies(f: FuncBuilder, x: Probe) -> None:
    first = f.let("sr_first", x.Pair, x.Pair.of(lo=x.au, hi=x.bu))
    second = f.let("sr_second", x.Pair, first)
    f.set(second.field("lo"), u32(777))
    f.ret(shape(first.field("lo"), second.field("lo")))


@branch("element-read-copies")
def _element_read_copies(f: FuncBuilder, x: Probe) -> None:
    bag = f.let("er_bag", vec(x.Pair, 8))
    f.push(bag, x.Pair.of(lo=x.au, hi=x.bu))
    held = f.let("er_held", x.Pair, bag.at(u32(0)))
    f.set(held.field("lo"), u32(777))
    f.ret(shape(bag.at(u32(0)).field("lo"), held.field("lo")))


@branch("nested-field-read-copies")
def _nested_field_read_copies(f: FuncBuilder, x: Probe) -> None:
    outer = f.let(
        "nf_outer", x.Nest, x.Nest.of(pair=x.Pair.of(lo=x.au, hi=x.bu), tag=u32(1))
    )
    held = f.let("nf_held", x.Pair, outer.field("pair"))
    f.set(held.field("lo"), u32(777))
    f.ret(shape(outer.field("pair").field("lo"), held.field("lo")))


@branch("element-write-reaches-storage")
def _element_write_reaches_storage(f: FuncBuilder, x: Probe) -> None:
    bag = f.let("ew_bag", vec(x.Pair, 8))
    f.push(bag, x.Pair.of(lo=x.au, hi=x.bu))
    f.set(bag.at(u32(0)).field("lo"), u32(777))
    f.ret(shape(bag.at(u32(0)).field("lo"), bag.at(u32(0)).field("hi")))


# --- inout, which JavaScript passes as a cell and Go as a pointer ---


@branch("inout-local")
def _inout_local(f: FuncBuilder, x: Probe) -> None:
    held = f.let("il_held", u32, x.au)
    f.call("bump", [inout(held), x.bu])
    f.ret(held.cast(counter))


@branch("inout-element")
def _inout_element(f: FuncBuilder, x: Probe) -> None:
    bag = f.let("ie_bag", vec(u32, 40))
    f.push(bag, x.au)
    f.call("bump", [inout(bag.at(u32(0))), x.bu])
    f.ret(bag.at(u32(0)).cast(counter))


@branch("inout-field")
def _inout_field(f: FuncBuilder, x: Probe) -> None:
    held = f.let("if_held", x.Pair, x.Pair.of(lo=x.au, hi=u32(0)))
    f.call("bump", [inout(held.field("lo")), x.bu])
    f.ret(shape(held.field("lo"), held.field("hi")))


@branch("inout-struct")
def _inout_struct(f: FuncBuilder, x: Probe) -> None:
    held = f.let("is_held", x.Pair, x.Pair.of(lo=x.au, hi=x.bu))
    f.call("swap_pair", [inout(held)])
    f.ret(shape(held.field("lo"), held.field("hi")))


# --- one branch per JavaScript backing store, since the engine only uses two ---


@branch("vec-bool", WORDS)
def _vec_bool(f: FuncBuilder, x: Probe) -> None:
    bag = f.let("vb_bag", vec(boolean, 40))
    f.push(bag, x.au < x.bu)
    f.push(bag, x.au > x.bu)
    f.ret(shape(bag.at(u32(0)).cast(u32), bag.at(u32(1)).cast(u32)))


@branch("vec-u8", WORDS)
def _vec_u8(f: FuncBuilder, x: Probe) -> None:
    bag = f.let("v8_bag", vec(u8, 40))
    f.push(bag, x.a8)
    f.push(bag, x.b8)
    f.ret(shape(bag.at(u32(0)).cast(u32), bag.at(u32(1)).cast(u32)))


@branch("vec-i32", WORDS)
def _vec_i32(f: FuncBuilder, x: Probe) -> None:
    bag = f.let("vi_bag", vec(i32, 40))
    f.push(bag, x.ai)
    f.push(bag, x.bi)
    f.ret(shape(bag.at(u32(0)).cast(u32), bag.at(u32(1)).cast(u32)))


@branch("vec-counter", COUNTS)
def _vec_counter(f: FuncBuilder, x: Probe) -> None:
    # A Float64Array holds every counter exactly, which is the whole reason
    # counter saturates at 2^53 - 1 rather than anywhere else.
    bag = f.let("vc_bag", vec(counter, 40))
    f.push(bag, x.a)
    f.push(bag, x.b)
    f.ret(bag.at(u32(0)) + bag.at(u32(1)))


@branch("vec-enum", WORDS)
def _vec_enum(f: FuncBuilder, x: Probe) -> None:
    bag = f.let("ve_bag", vec(x.Colour, 40))
    f.push(bag, x.Colour.Green)
    f.push(bag, x.Colour.Blue)
    f.ret(shape((bag.at(u32(0)) == x.Colour.Green).cast(u32), (bag.at(u32(1)) == x.Colour.Blue).cast(u32)))


@branch("vec-frozen", WORDS)
def _vec_frozen(f: FuncBuilder, x: Probe) -> None:
    bag = f.let("vf_bag", vec(frozen(bytes_), 8))
    f.push(bag, x.table)
    f.ret(shape(bag.at(u32(0)).len(), bag.at(u32(0)).at(x.au & u32(15)).cast(u32)))


# --- switch, which Go prints as a switch and JavaScript as an if-chain ---


@branch("switch-covers-the-enum", ONE_SIZE)
def _switch_covers_the_enum(f: FuncBuilder, x: Probe) -> None:
    picked = f.let("sc_picked", x.Colour)
    with f.if_(x.au == u32(0)):
        f.set(picked, x.Colour.Red)
    with f.else_():
        with f.if_(x.au == u32(1)):
            f.set(picked, x.Colour.Green)
        with f.else_():
            f.set(picked, x.Colour.Blue)
    answer = f.let("sc_answer", u32, u32(0))
    with f.switch(picked) as arms:
        with arms.case("Red"):
            f.set(answer, u32(10))
        with arms.case("Green"):
            f.set(answer, u32(20))
        with arms.case("Blue"):
            f.set(answer, u32(30))
    f.ret(answer.cast(counter))


@branch("switch-with-a-default", ONE_SIZE)
def _switch_with_a_default(f: FuncBuilder, x: Probe) -> None:
    picked = f.let("sd_picked", x.Colour)
    with f.if_(x.au == u32(1)):
        f.set(picked, x.Colour.Green)
    answer = f.let("sd_answer", u32, u32(7))
    with f.switch(picked) as arms:
        # An arm that does nothing still has to be its own branch, or control
        # would fall into the default.
        with arms.case("Green"):
            pass
        with arms.otherwise():
            f.set(answer, u32(99))
    f.ret(answer.cast(counter))


@branch("break-out-of-a-switch", ONE_SIZE)
def _break_out_of_a_switch(f: FuncBuilder, x: Probe) -> None:
    # A TIR break inside a switch arm belongs to the loop, which is why Go gets
    # a labelled loop and JavaScript an if-chain rather than a switch.
    i = f.let("bs_i", u32, u32(0))
    total = f.let("bs_total", u32, u32(0))
    with f.while_(i < u32(40), (u32(40) - i).cast(counter)):
        picked = f.let("bs_picked", x.Colour)
        with f.if_(i == x.au):
            f.set(picked, x.Colour.Red)
        with f.else_():
            f.set(picked, x.Colour.Green)
        with f.switch(picked) as arms:
            with arms.case("Red"):
                f.brk()
            with arms.otherwise():
                f.set(total, total + u32(1))
        f.set(i, i + u32(1))
    f.ret(shape(i, total))


@branch("take-and-swap")
def _take_and_swap(f: FuncBuilder, x: Probe) -> None:
    left = f.let("ts_left", u32, x.au)
    right = f.let("ts_right", u32, x.bu)
    f.swap(left, right)
    emptied = f.let("ts_emptied", u32, u32(0))
    f.take(emptied, left)
    f.ret(shape(emptied, left))


# --- named constants, which only Go treats as anything special ---
#
# It folds a use of one at compile time and then refuses the overflow TIR
# defines, exactly as it does for a literal, so `tir_k` has to stand between
# the two. Every branch here would be a Go build error without it, which makes
# them the one part of the probe that fails loudly rather than quietly.


@branch("const-u32-add-literal", NO_OPERANDS)
def _const_u32_add_literal(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.BIGU + u32(BIG_U32)).cast(counter))


@branch("const-u32-add-const", NO_OPERANDS)
def _const_u32_add_const(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.BIGU + x.BIGU).cast(counter))


@branch("const-u32-neg", NO_OPERANDS)
def _const_u32_neg(f: FuncBuilder, x: Probe) -> None:
    f.ret((-x.BIGU).cast(counter))


@branch("const-u32-shl", NO_OPERANDS)
def _const_u32_shl(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.BIGU.shl(5).cast(counter))


@branch("const-u32-to-u8", NO_OPERANDS)
def _const_u32_to_u8(f: FuncBuilder, x: Probe) -> None:
    f.ret(x.BIGU.cast(u8).cast(counter))


@branch("const-i32-add", NO_OPERANDS)
def _const_i32_add(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.BIGI + x.BIGI).cast(u32).cast(counter))


@branch("const-i32-neg", NO_OPERANDS)
def _const_i32_neg(f: FuncBuilder, x: Probe) -> None:
    # -MIN is MIN, which is a wrap in TIR and an overflow to Go.
    f.ret((-x.MINI).cast(u32).cast(counter))


@branch("const-u8-add", NO_OPERANDS)
def _const_u8_add(f: FuncBuilder, x: Probe) -> None:
    f.ret((x.BIGB + x.BIGB).cast(counter))


@branch("const-counter-to-u32", NO_OPERANDS)
def _const_counter_to_u32(f: FuncBuilder, x: Probe) -> None:
    # A counter's own arithmetic is a helper call and so never constant, but a
    # cast of one is, and the cap does not fit in a u32.
    f.ret(x.BIGC.cast(u32).cast(counter))


def cases() -> list[tuple[str, int, int, int, int]]:
    """Every case, with the answer the reference interpreter gives."""
    from ..tir.interp import Interpreter

    built = program()
    out = []
    for kind, (name, _, operands) in enumerate(BRANCHES):
        for a, b in operands:
            answer = Interpreter(built).call("probe", [kind, a, b])
            assert isinstance(answer, int)
            out.append((name, kind, a, b, answer))
    return out


def corpus() -> dict:
    """The probe corpus as plain JSON data."""
    return conformance.document(
        NOTE,
        [
            {"name": name, "kind": kind, "a": a, "b": b, "expect": answer}
            for name, kind, a, b, answer in cases()
        ],
        shift=SHIFT,
    )


def corpus_text() -> str:
    return conformance.text(corpus())


@functools.lru_cache(maxsize=1)
def program() -> ir.Program:
    """The probe, built once per process and validated."""
    from ..tir import validate

    built = build()
    validate(built)
    return built


def build() -> ir.Program:
    """The probe, as one TIR program."""
    m = Module()

    pair = m.struct("Pair", [("lo", u32), ("hi", u32)])
    nest = m.struct("Nest", [("pair", pair), ("tag", u32)])
    colour = m.enum("Colour", ["Red", "Green", "Blue"])
    table = m.const("TABLE", frozen(bytes_), TABLE)
    scalars = {
        "BIGU": m.const("BIGU", u32, BIG_U32),
        "BIGI": m.const("BIGI", i32, BIG_I32),
        "MINI": m.const("MINI", i32, MIN_I32),
        "BIGB": m.const("BIGB", u8, BIG_U8),
        "BIGC": m.const("BIGC", counter, CAP),
    }

    bump = m.func("bump", params=[("slot", u32, "inout"), ("by", u32)])
    bump.set(bump["slot"], bump["slot"] + bump["by"])

    swap_pair = m.func("swap_pair", params=[("p", pair, "inout")])
    held = swap_pair.let("held", u32, swap_pair["p"].field("lo"))
    swap_pair.set(swap_pair["p"].field("lo"), swap_pair["p"].field("hi"))
    swap_pair.set(swap_pair["p"].field("hi"), held)

    f = m.func("probe", params=[("kind", u32), ("a", counter), ("b", counter)], ret=counter)
    x = Probe(f, pair, nest, colour, table, scalars)
    for index, (_, emit, _operands) in enumerate(BRANCHES):
        with f.if_(f["kind"] == u32(index)):
            emit(f, x)
    f.ret(counter(0))

    return m.build()


__all__ = ["BRANCHES", "NOTE", "PATH", "SHIFT", "cases", "corpus", "corpus_text", "kinds", "program"]
